// Code generated by counterfeiter. DO NOT EDIT.
package driverfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/driver"
	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeHeadStater struct {
	StatObjectStub        func(context.Context, *op.BucketRecord, meta.ObjKey) (*op.ObjectState, error)
	statObjectMutex       sync.RWMutex
	statObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
	}
	statObjectReturns struct {
		result1 *op.ObjectState
		result2 error
	}
	statObjectReturnsOnCall map[int]struct {
		result1 *op.ObjectState
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHeadStater) StatObject(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.ObjKey) (*op.ObjectState, error) {
	fake.statObjectMutex.Lock()
	ret, specificReturn := fake.statObjectReturnsOnCall[len(fake.statObjectArgsForCall)]
	fake.statObjectArgsForCall = append(fake.statObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
	}{arg1, arg2, arg3})
	stub := fake.StatObjectStub
	fakeReturns := fake.statObjectReturns
	fake.recordInvocation("StatObject", []interface{}{arg1, arg2, arg3})
	fake.statObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHeadStater) StatObjectCallCount() int {
	fake.statObjectMutex.RLock()
	defer fake.statObjectMutex.RUnlock()
	return len(fake.statObjectArgsForCall)
}

func (fake *FakeHeadStater) StatObjectCalls(stub func(context.Context, *op.BucketRecord, meta.ObjKey) (*op.ObjectState, error)) {
	fake.statObjectMutex.Lock()
	defer fake.statObjectMutex.Unlock()
	fake.StatObjectStub = stub
}

func (fake *FakeHeadStater) StatObjectArgsForCall(i int) (context.Context, *op.BucketRecord, meta.ObjKey) {
	fake.statObjectMutex.RLock()
	defer fake.statObjectMutex.RUnlock()
	argsForCall := fake.statObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeHeadStater) StatObjectReturns(result1 *op.ObjectState, result2 error) {
	fake.statObjectMutex.Lock()
	defer fake.statObjectMutex.Unlock()
	fake.StatObjectStub = nil
	fake.statObjectReturns = struct {
		result1 *op.ObjectState
		result2 error
	}{result1, result2}
}

func (fake *FakeHeadStater) StatObjectReturnsOnCall(i int, result1 *op.ObjectState, result2 error) {
	fake.statObjectMutex.Lock()
	defer fake.statObjectMutex.Unlock()
	fake.StatObjectStub = nil
	if fake.statObjectReturnsOnCall == nil {
		fake.statObjectReturnsOnCall = make(map[int]struct {
			result1 *op.ObjectState
			result2 error
		})
	}
	fake.statObjectReturnsOnCall[i] = struct {
		result1 *op.ObjectState
		result2 error
	}{result1, result2}
}

func (fake *FakeHeadStater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHeadStater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.HeadStater = new(FakeHeadStater)
