// Code generated by counterfeiter. DO NOT EDIT.
package radosclientfakes

import (
	"context"
	"sync"
	"time"

	"github.com/jhoblitt/rgw-go/internal/radosclient"
)

type FakePool struct {
	BreakLockStub        func(context.Context, string, string, string, string) error
	breakLockMutex       sync.RWMutex
	breakLockArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	breakLockReturns struct {
		result1 error
	}
	breakLockReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	IDStub        func() int64
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
	}
	iDReturns struct {
		result1 int64
	}
	iDReturnsOnCall map[int]struct {
		result1 int64
	}
	ListLockersStub        func(context.Context, string, string) ([]radosclient.Locker, error)
	listLockersMutex       sync.RWMutex
	listLockersArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	listLockersReturns struct {
		result1 []radosclient.Locker
		result2 error
	}
	listLockersReturnsOnCall map[int]struct {
		result1 []radosclient.Locker
		result2 error
	}
	ListObjectsStub        func(context.Context, func(oid string, locator string) error) error
	listObjectsMutex       sync.RWMutex
	listObjectsArgsForCall []struct {
		arg1 context.Context
		arg2 func(oid string, locator string) error
	}
	listObjectsReturns struct {
		result1 error
	}
	listObjectsReturnsOnCall map[int]struct {
		result1 error
	}
	LockExclusiveStub        func(context.Context, string, string, string, string, time.Duration, radosclient.LockFlags) error
	lockExclusiveMutex       sync.RWMutex
	lockExclusiveArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 time.Duration
		arg7 radosclient.LockFlags
	}
	lockExclusiveReturns struct {
		result1 error
	}
	lockExclusiveReturnsOnCall map[int]struct {
		result1 error
	}
	LockSharedStub        func(context.Context, string, string, string, string, string, time.Duration, radosclient.LockFlags) error
	lockSharedMutex       sync.RWMutex
	lockSharedArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
		arg7 time.Duration
		arg8 radosclient.LockFlags
	}
	lockSharedReturns struct {
		result1 error
	}
	lockSharedReturnsOnCall map[int]struct {
		result1 error
	}
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	NamespaceStub        func() string
	namespaceMutex       sync.RWMutex
	namespaceArgsForCall []struct {
	}
	namespaceReturns struct {
		result1 string
	}
	namespaceReturnsOnCall map[int]struct {
		result1 string
	}
	NotifyStub        func(context.Context, string, []byte, time.Duration) ([]radosclient.NotifyAck, error)
	notifyMutex       sync.RWMutex
	notifyArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 time.Duration
	}
	notifyReturns struct {
		result1 []radosclient.NotifyAck
		result2 error
	}
	notifyReturnsOnCall map[int]struct {
		result1 []radosclient.NotifyAck
		result2 error
	}
	ReadStub        func(context.Context, string, *radosclient.ReadOp, radosclient.OpFlags) (uint64, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *radosclient.ReadOp
		arg4 radosclient.OpFlags
	}
	readReturns struct {
		result1 uint64
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 uint64
		result2 error
	}
	RequiredAlignmentStub        func(context.Context) (uint64, error)
	requiredAlignmentMutex       sync.RWMutex
	requiredAlignmentArgsForCall []struct {
		arg1 context.Context
	}
	requiredAlignmentReturns struct {
		result1 uint64
		result2 error
	}
	requiredAlignmentReturnsOnCall map[int]struct {
		result1 uint64
		result2 error
	}
	UnlockStub        func(context.Context, string, string, string) error
	unlockMutex       sync.RWMutex
	unlockArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	unlockReturns struct {
		result1 error
	}
	unlockReturnsOnCall map[int]struct {
		result1 error
	}
	WatchStub        func(context.Context, string, func(notifyID uint64, notifierID uint64, payload []byte)) (radosclient.Watch, error)
	watchMutex       sync.RWMutex
	watchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 func(notifyID uint64, notifierID uint64, payload []byte)
	}
	watchReturns struct {
		result1 radosclient.Watch
		result2 error
	}
	watchReturnsOnCall map[int]struct {
		result1 radosclient.Watch
		result2 error
	}
	WithLocatorStub        func(string) radosclient.Pool
	withLocatorMutex       sync.RWMutex
	withLocatorArgsForCall []struct {
		arg1 string
	}
	withLocatorReturns struct {
		result1 radosclient.Pool
	}
	withLocatorReturnsOnCall map[int]struct {
		result1 radosclient.Pool
	}
	WriteStub        func(context.Context, string, *radosclient.WriteOp, radosclient.OpFlags) (uint64, error)
	writeMutex       sync.RWMutex
	writeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *radosclient.WriteOp
		arg4 radosclient.OpFlags
	}
	writeReturns struct {
		result1 uint64
		result2 error
	}
	writeReturnsOnCall map[int]struct {
		result1 uint64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePool) BreakLock(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) error {
	fake.breakLockMutex.Lock()
	ret, specificReturn := fake.breakLockReturnsOnCall[len(fake.breakLockArgsForCall)]
	fake.breakLockArgsForCall = append(fake.breakLockArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.BreakLockStub
	fakeReturns := fake.breakLockReturns
	fake.recordInvocation("BreakLock", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.breakLockMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) BreakLockCallCount() int {
	fake.breakLockMutex.RLock()
	defer fake.breakLockMutex.RUnlock()
	return len(fake.breakLockArgsForCall)
}

func (fake *FakePool) BreakLockCalls(stub func(context.Context, string, string, string, string) error) {
	fake.breakLockMutex.Lock()
	defer fake.breakLockMutex.Unlock()
	fake.BreakLockStub = stub
}

func (fake *FakePool) BreakLockArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.breakLockMutex.RLock()
	defer fake.breakLockMutex.RUnlock()
	argsForCall := fake.breakLockArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakePool) BreakLockReturns(result1 error) {
	fake.breakLockMutex.Lock()
	defer fake.breakLockMutex.Unlock()
	fake.BreakLockStub = nil
	fake.breakLockReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) BreakLockReturnsOnCall(i int, result1 error) {
	fake.breakLockMutex.Lock()
	defer fake.breakLockMutex.Unlock()
	fake.BreakLockStub = nil
	if fake.breakLockReturnsOnCall == nil {
		fake.breakLockReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.breakLockReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakePool) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakePool) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) ID() int64 {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
	}{})
	stub := fake.IDStub
	fakeReturns := fake.iDReturns
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *FakePool) IDCalls(stub func() int64) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *FakePool) IDReturns(result1 int64) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 int64
	}{result1}
}

func (fake *FakePool) IDReturnsOnCall(i int, result1 int64) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 int64
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 int64
	}{result1}
}

func (fake *FakePool) ListLockers(arg1 context.Context, arg2 string, arg3 string) ([]radosclient.Locker, error) {
	fake.listLockersMutex.Lock()
	ret, specificReturn := fake.listLockersReturnsOnCall[len(fake.listLockersArgsForCall)]
	fake.listLockersArgsForCall = append(fake.listLockersArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ListLockersStub
	fakeReturns := fake.listLockersReturns
	fake.recordInvocation("ListLockers", []interface{}{arg1, arg2, arg3})
	fake.listLockersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePool) ListLockersCallCount() int {
	fake.listLockersMutex.RLock()
	defer fake.listLockersMutex.RUnlock()
	return len(fake.listLockersArgsForCall)
}

func (fake *FakePool) ListLockersCalls(stub func(context.Context, string, string) ([]radosclient.Locker, error)) {
	fake.listLockersMutex.Lock()
	defer fake.listLockersMutex.Unlock()
	fake.ListLockersStub = stub
}

func (fake *FakePool) ListLockersArgsForCall(i int) (context.Context, string, string) {
	fake.listLockersMutex.RLock()
	defer fake.listLockersMutex.RUnlock()
	argsForCall := fake.listLockersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePool) ListLockersReturns(result1 []radosclient.Locker, result2 error) {
	fake.listLockersMutex.Lock()
	defer fake.listLockersMutex.Unlock()
	fake.ListLockersStub = nil
	fake.listLockersReturns = struct {
		result1 []radosclient.Locker
		result2 error
	}{result1, result2}
}

func (fake *FakePool) ListLockersReturnsOnCall(i int, result1 []radosclient.Locker, result2 error) {
	fake.listLockersMutex.Lock()
	defer fake.listLockersMutex.Unlock()
	fake.ListLockersStub = nil
	if fake.listLockersReturnsOnCall == nil {
		fake.listLockersReturnsOnCall = make(map[int]struct {
			result1 []radosclient.Locker
			result2 error
		})
	}
	fake.listLockersReturnsOnCall[i] = struct {
		result1 []radosclient.Locker
		result2 error
	}{result1, result2}
}

func (fake *FakePool) ListObjects(arg1 context.Context, arg2 func(oid string, locator string) error) error {
	fake.listObjectsMutex.Lock()
	ret, specificReturn := fake.listObjectsReturnsOnCall[len(fake.listObjectsArgsForCall)]
	fake.listObjectsArgsForCall = append(fake.listObjectsArgsForCall, struct {
		arg1 context.Context
		arg2 func(oid string, locator string) error
	}{arg1, arg2})
	stub := fake.ListObjectsStub
	fakeReturns := fake.listObjectsReturns
	fake.recordInvocation("ListObjects", []interface{}{arg1, arg2})
	fake.listObjectsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) ListObjectsCallCount() int {
	fake.listObjectsMutex.RLock()
	defer fake.listObjectsMutex.RUnlock()
	return len(fake.listObjectsArgsForCall)
}

func (fake *FakePool) ListObjectsCalls(stub func(context.Context, func(oid string, locator string) error) error) {
	fake.listObjectsMutex.Lock()
	defer fake.listObjectsMutex.Unlock()
	fake.ListObjectsStub = stub
}

func (fake *FakePool) ListObjectsArgsForCall(i int) (context.Context, func(oid string, locator string) error) {
	fake.listObjectsMutex.RLock()
	defer fake.listObjectsMutex.RUnlock()
	argsForCall := fake.listObjectsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePool) ListObjectsReturns(result1 error) {
	fake.listObjectsMutex.Lock()
	defer fake.listObjectsMutex.Unlock()
	fake.ListObjectsStub = nil
	fake.listObjectsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) ListObjectsReturnsOnCall(i int, result1 error) {
	fake.listObjectsMutex.Lock()
	defer fake.listObjectsMutex.Unlock()
	fake.ListObjectsStub = nil
	if fake.listObjectsReturnsOnCall == nil {
		fake.listObjectsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.listObjectsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) LockExclusive(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string, arg6 time.Duration, arg7 radosclient.LockFlags) error {
	fake.lockExclusiveMutex.Lock()
	ret, specificReturn := fake.lockExclusiveReturnsOnCall[len(fake.lockExclusiveArgsForCall)]
	fake.lockExclusiveArgsForCall = append(fake.lockExclusiveArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 time.Duration
		arg7 radosclient.LockFlags
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	stub := fake.LockExclusiveStub
	fakeReturns := fake.lockExclusiveReturns
	fake.recordInvocation("LockExclusive", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.lockExclusiveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) LockExclusiveCallCount() int {
	fake.lockExclusiveMutex.RLock()
	defer fake.lockExclusiveMutex.RUnlock()
	return len(fake.lockExclusiveArgsForCall)
}

func (fake *FakePool) LockExclusiveCalls(stub func(context.Context, string, string, string, string, time.Duration, radosclient.LockFlags) error) {
	fake.lockExclusiveMutex.Lock()
	defer fake.lockExclusiveMutex.Unlock()
	fake.LockExclusiveStub = stub
}

func (fake *FakePool) LockExclusiveArgsForCall(i int) (context.Context, string, string, string, string, time.Duration, radosclient.LockFlags) {
	fake.lockExclusiveMutex.RLock()
	defer fake.lockExclusiveMutex.RUnlock()
	argsForCall := fake.lockExclusiveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7
}

func (fake *FakePool) LockExclusiveReturns(result1 error) {
	fake.lockExclusiveMutex.Lock()
	defer fake.lockExclusiveMutex.Unlock()
	fake.LockExclusiveStub = nil
	fake.lockExclusiveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) LockExclusiveReturnsOnCall(i int, result1 error) {
	fake.lockExclusiveMutex.Lock()
	defer fake.lockExclusiveMutex.Unlock()
	fake.LockExclusiveStub = nil
	if fake.lockExclusiveReturnsOnCall == nil {
		fake.lockExclusiveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.lockExclusiveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) LockShared(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string, arg6 string, arg7 time.Duration, arg8 radosclient.LockFlags) error {
	fake.lockSharedMutex.Lock()
	ret, specificReturn := fake.lockSharedReturnsOnCall[len(fake.lockSharedArgsForCall)]
	fake.lockSharedArgsForCall = append(fake.lockSharedArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
		arg7 time.Duration
		arg8 radosclient.LockFlags
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8})
	stub := fake.LockSharedStub
	fakeReturns := fake.lockSharedReturns
	fake.recordInvocation("LockShared", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8})
	fake.lockSharedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) LockSharedCallCount() int {
	fake.lockSharedMutex.RLock()
	defer fake.lockSharedMutex.RUnlock()
	return len(fake.lockSharedArgsForCall)
}

func (fake *FakePool) LockSharedCalls(stub func(context.Context, string, string, string, string, string, time.Duration, radosclient.LockFlags) error) {
	fake.lockSharedMutex.Lock()
	defer fake.lockSharedMutex.Unlock()
	fake.LockSharedStub = stub
}

func (fake *FakePool) LockSharedArgsForCall(i int) (context.Context, string, string, string, string, string, time.Duration, radosclient.LockFlags) {
	fake.lockSharedMutex.RLock()
	defer fake.lockSharedMutex.RUnlock()
	argsForCall := fake.lockSharedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7, argsForCall.arg8
}

func (fake *FakePool) LockSharedReturns(result1 error) {
	fake.lockSharedMutex.Lock()
	defer fake.lockSharedMutex.Unlock()
	fake.LockSharedStub = nil
	fake.lockSharedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) LockSharedReturnsOnCall(i int, result1 error) {
	fake.lockSharedMutex.Lock()
	defer fake.lockSharedMutex.Unlock()
	fake.LockSharedStub = nil
	if fake.lockSharedReturnsOnCall == nil {
		fake.lockSharedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.lockSharedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakePool) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakePool) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakePool) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakePool) Namespace() string {
	fake.namespaceMutex.Lock()
	ret, specificReturn := fake.namespaceReturnsOnCall[len(fake.namespaceArgsForCall)]
	fake.namespaceArgsForCall = append(fake.namespaceArgsForCall, struct {
	}{})
	stub := fake.NamespaceStub
	fakeReturns := fake.namespaceReturns
	fake.recordInvocation("Namespace", []interface{}{})
	fake.namespaceMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) NamespaceCallCount() int {
	fake.namespaceMutex.RLock()
	defer fake.namespaceMutex.RUnlock()
	return len(fake.namespaceArgsForCall)
}

func (fake *FakePool) NamespaceCalls(stub func() string) {
	fake.namespaceMutex.Lock()
	defer fake.namespaceMutex.Unlock()
	fake.NamespaceStub = stub
}

func (fake *FakePool) NamespaceReturns(result1 string) {
	fake.namespaceMutex.Lock()
	defer fake.namespaceMutex.Unlock()
	fake.NamespaceStub = nil
	fake.namespaceReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakePool) NamespaceReturnsOnCall(i int, result1 string) {
	fake.namespaceMutex.Lock()
	defer fake.namespaceMutex.Unlock()
	fake.NamespaceStub = nil
	if fake.namespaceReturnsOnCall == nil {
		fake.namespaceReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.namespaceReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakePool) Notify(arg1 context.Context, arg2 string, arg3 []byte, arg4 time.Duration) ([]radosclient.NotifyAck, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.notifyMutex.Lock()
	ret, specificReturn := fake.notifyReturnsOnCall[len(fake.notifyArgsForCall)]
	fake.notifyArgsForCall = append(fake.notifyArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 time.Duration
	}{arg1, arg2, arg3Copy, arg4})
	stub := fake.NotifyStub
	fakeReturns := fake.notifyReturns
	fake.recordInvocation("Notify", []interface{}{arg1, arg2, arg3Copy, arg4})
	fake.notifyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePool) NotifyCallCount() int {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	return len(fake.notifyArgsForCall)
}

func (fake *FakePool) NotifyCalls(stub func(context.Context, string, []byte, time.Duration) ([]radosclient.NotifyAck, error)) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = stub
}

func (fake *FakePool) NotifyArgsForCall(i int) (context.Context, string, []byte, time.Duration) {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	argsForCall := fake.notifyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePool) NotifyReturns(result1 []radosclient.NotifyAck, result2 error) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = nil
	fake.notifyReturns = struct {
		result1 []radosclient.NotifyAck
		result2 error
	}{result1, result2}
}

func (fake *FakePool) NotifyReturnsOnCall(i int, result1 []radosclient.NotifyAck, result2 error) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = nil
	if fake.notifyReturnsOnCall == nil {
		fake.notifyReturnsOnCall = make(map[int]struct {
			result1 []radosclient.NotifyAck
			result2 error
		})
	}
	fake.notifyReturnsOnCall[i] = struct {
		result1 []radosclient.NotifyAck
		result2 error
	}{result1, result2}
}

func (fake *FakePool) Read(arg1 context.Context, arg2 string, arg3 *radosclient.ReadOp, arg4 radosclient.OpFlags) (uint64, error) {
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *radosclient.ReadOp
		arg4 radosclient.OpFlags
	}{arg1, arg2, arg3, arg4})
	stub := fake.ReadStub
	fakeReturns := fake.readReturns
	fake.recordInvocation("Read", []interface{}{arg1, arg2, arg3, arg4})
	fake.readMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePool) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakePool) ReadCalls(stub func(context.Context, string, *radosclient.ReadOp, radosclient.OpFlags) (uint64, error)) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = stub
}

func (fake *FakePool) ReadArgsForCall(i int) (context.Context, string, *radosclient.ReadOp, radosclient.OpFlags) {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	argsForCall := fake.readArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePool) ReadReturns(result1 uint64, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakePool) ReadReturnsOnCall(i int, result1 uint64, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 error
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakePool) RequiredAlignment(arg1 context.Context) (uint64, error) {
	fake.requiredAlignmentMutex.Lock()
	ret, specificReturn := fake.requiredAlignmentReturnsOnCall[len(fake.requiredAlignmentArgsForCall)]
	fake.requiredAlignmentArgsForCall = append(fake.requiredAlignmentArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RequiredAlignmentStub
	fakeReturns := fake.requiredAlignmentReturns
	fake.recordInvocation("RequiredAlignment", []interface{}{arg1})
	fake.requiredAlignmentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePool) RequiredAlignmentCallCount() int {
	fake.requiredAlignmentMutex.RLock()
	defer fake.requiredAlignmentMutex.RUnlock()
	return len(fake.requiredAlignmentArgsForCall)
}

func (fake *FakePool) RequiredAlignmentCalls(stub func(context.Context) (uint64, error)) {
	fake.requiredAlignmentMutex.Lock()
	defer fake.requiredAlignmentMutex.Unlock()
	fake.RequiredAlignmentStub = stub
}

func (fake *FakePool) RequiredAlignmentArgsForCall(i int) context.Context {
	fake.requiredAlignmentMutex.RLock()
	defer fake.requiredAlignmentMutex.RUnlock()
	argsForCall := fake.requiredAlignmentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePool) RequiredAlignmentReturns(result1 uint64, result2 error) {
	fake.requiredAlignmentMutex.Lock()
	defer fake.requiredAlignmentMutex.Unlock()
	fake.RequiredAlignmentStub = nil
	fake.requiredAlignmentReturns = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakePool) RequiredAlignmentReturnsOnCall(i int, result1 uint64, result2 error) {
	fake.requiredAlignmentMutex.Lock()
	defer fake.requiredAlignmentMutex.Unlock()
	fake.RequiredAlignmentStub = nil
	if fake.requiredAlignmentReturnsOnCall == nil {
		fake.requiredAlignmentReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 error
		})
	}
	fake.requiredAlignmentReturnsOnCall[i] = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakePool) Unlock(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.unlockMutex.Lock()
	ret, specificReturn := fake.unlockReturnsOnCall[len(fake.unlockArgsForCall)]
	fake.unlockArgsForCall = append(fake.unlockArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.UnlockStub
	fakeReturns := fake.unlockReturns
	fake.recordInvocation("Unlock", []interface{}{arg1, arg2, arg3, arg4})
	fake.unlockMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) UnlockCallCount() int {
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	return len(fake.unlockArgsForCall)
}

func (fake *FakePool) UnlockCalls(stub func(context.Context, string, string, string) error) {
	fake.unlockMutex.Lock()
	defer fake.unlockMutex.Unlock()
	fake.UnlockStub = stub
}

func (fake *FakePool) UnlockArgsForCall(i int) (context.Context, string, string, string) {
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	argsForCall := fake.unlockArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePool) UnlockReturns(result1 error) {
	fake.unlockMutex.Lock()
	defer fake.unlockMutex.Unlock()
	fake.UnlockStub = nil
	fake.unlockReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) UnlockReturnsOnCall(i int, result1 error) {
	fake.unlockMutex.Lock()
	defer fake.unlockMutex.Unlock()
	fake.UnlockStub = nil
	if fake.unlockReturnsOnCall == nil {
		fake.unlockReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unlockReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePool) Watch(arg1 context.Context, arg2 string, arg3 func(notifyID uint64, notifierID uint64, payload []byte)) (radosclient.Watch, error) {
	fake.watchMutex.Lock()
	ret, specificReturn := fake.watchReturnsOnCall[len(fake.watchArgsForCall)]
	fake.watchArgsForCall = append(fake.watchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 func(notifyID uint64, notifierID uint64, payload []byte)
	}{arg1, arg2, arg3})
	stub := fake.WatchStub
	fakeReturns := fake.watchReturns
	fake.recordInvocation("Watch", []interface{}{arg1, arg2, arg3})
	fake.watchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePool) WatchCallCount() int {
	fake.watchMutex.RLock()
	defer fake.watchMutex.RUnlock()
	return len(fake.watchArgsForCall)
}

func (fake *FakePool) WatchCalls(stub func(context.Context, string, func(notifyID uint64, notifierID uint64, payload []byte)) (radosclient.Watch, error)) {
	fake.watchMutex.Lock()
	defer fake.watchMutex.Unlock()
	fake.WatchStub = stub
}

func (fake *FakePool) WatchArgsForCall(i int) (context.Context, string, func(notifyID uint64, notifierID uint64, payload []byte)) {
	fake.watchMutex.RLock()
	defer fake.watchMutex.RUnlock()
	argsForCall := fake.watchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePool) WatchReturns(result1 radosclient.Watch, result2 error) {
	fake.watchMutex.Lock()
	defer fake.watchMutex.Unlock()
	fake.WatchStub = nil
	fake.watchReturns = struct {
		result1 radosclient.Watch
		result2 error
	}{result1, result2}
}

func (fake *FakePool) WatchReturnsOnCall(i int, result1 radosclient.Watch, result2 error) {
	fake.watchMutex.Lock()
	defer fake.watchMutex.Unlock()
	fake.WatchStub = nil
	if fake.watchReturnsOnCall == nil {
		fake.watchReturnsOnCall = make(map[int]struct {
			result1 radosclient.Watch
			result2 error
		})
	}
	fake.watchReturnsOnCall[i] = struct {
		result1 radosclient.Watch
		result2 error
	}{result1, result2}
}

func (fake *FakePool) WithLocator(arg1 string) radosclient.Pool {
	fake.withLocatorMutex.Lock()
	ret, specificReturn := fake.withLocatorReturnsOnCall[len(fake.withLocatorArgsForCall)]
	fake.withLocatorArgsForCall = append(fake.withLocatorArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.WithLocatorStub
	fakeReturns := fake.withLocatorReturns
	fake.recordInvocation("WithLocator", []interface{}{arg1})
	fake.withLocatorMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePool) WithLocatorCallCount() int {
	fake.withLocatorMutex.RLock()
	defer fake.withLocatorMutex.RUnlock()
	return len(fake.withLocatorArgsForCall)
}

func (fake *FakePool) WithLocatorCalls(stub func(string) radosclient.Pool) {
	fake.withLocatorMutex.Lock()
	defer fake.withLocatorMutex.Unlock()
	fake.WithLocatorStub = stub
}

func (fake *FakePool) WithLocatorArgsForCall(i int) string {
	fake.withLocatorMutex.RLock()
	defer fake.withLocatorMutex.RUnlock()
	argsForCall := fake.withLocatorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePool) WithLocatorReturns(result1 radosclient.Pool) {
	fake.withLocatorMutex.Lock()
	defer fake.withLocatorMutex.Unlock()
	fake.WithLocatorStub = nil
	fake.withLocatorReturns = struct {
		result1 radosclient.Pool
	}{result1}
}

func (fake *FakePool) WithLocatorReturnsOnCall(i int, result1 radosclient.Pool) {
	fake.withLocatorMutex.Lock()
	defer fake.withLocatorMutex.Unlock()
	fake.WithLocatorStub = nil
	if fake.withLocatorReturnsOnCall == nil {
		fake.withLocatorReturnsOnCall = make(map[int]struct {
			result1 radosclient.Pool
		})
	}
	fake.withLocatorReturnsOnCall[i] = struct {
		result1 radosclient.Pool
	}{result1}
}

func (fake *FakePool) Write(arg1 context.Context, arg2 string, arg3 *radosclient.WriteOp, arg4 radosclient.OpFlags) (uint64, error) {
	fake.writeMutex.Lock()
	ret, specificReturn := fake.writeReturnsOnCall[len(fake.writeArgsForCall)]
	fake.writeArgsForCall = append(fake.writeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *radosclient.WriteOp
		arg4 radosclient.OpFlags
	}{arg1, arg2, arg3, arg4})
	stub := fake.WriteStub
	fakeReturns := fake.writeReturns
	fake.recordInvocation("Write", []interface{}{arg1, arg2, arg3, arg4})
	fake.writeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePool) WriteCallCount() int {
	fake.writeMutex.RLock()
	defer fake.writeMutex.RUnlock()
	return len(fake.writeArgsForCall)
}

func (fake *FakePool) WriteCalls(stub func(context.Context, string, *radosclient.WriteOp, radosclient.OpFlags) (uint64, error)) {
	fake.writeMutex.Lock()
	defer fake.writeMutex.Unlock()
	fake.WriteStub = stub
}

func (fake *FakePool) WriteArgsForCall(i int) (context.Context, string, *radosclient.WriteOp, radosclient.OpFlags) {
	fake.writeMutex.RLock()
	defer fake.writeMutex.RUnlock()
	argsForCall := fake.writeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePool) WriteReturns(result1 uint64, result2 error) {
	fake.writeMutex.Lock()
	defer fake.writeMutex.Unlock()
	fake.WriteStub = nil
	fake.writeReturns = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakePool) WriteReturnsOnCall(i int, result1 uint64, result2 error) {
	fake.writeMutex.Lock()
	defer fake.writeMutex.Unlock()
	fake.WriteStub = nil
	if fake.writeReturnsOnCall == nil {
		fake.writeReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 error
		})
	}
	fake.writeReturnsOnCall[i] = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *FakePool) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePool) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ radosclient.Pool = new(FakePool)
