// Code generated by counterfeiter. DO NOT EDIT.
package radosclientfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/radosclient"
)

type FakeCluster struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ConfigGetStub        func(string) (string, error)
	configGetMutex       sync.RWMutex
	configGetArgsForCall []struct {
		arg1 string
	}
	configGetReturns struct {
		result1 string
		result2 error
	}
	configGetReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FSIDStub        func() (string, error)
	fSIDMutex       sync.RWMutex
	fSIDArgsForCall []struct {
	}
	fSIDReturns struct {
		result1 string
		result2 error
	}
	fSIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	InstanceIDStub        func() uint64
	instanceIDMutex       sync.RWMutex
	instanceIDArgsForCall []struct {
	}
	instanceIDReturns struct {
		result1 uint64
	}
	instanceIDReturnsOnCall map[int]struct {
		result1 uint64
	}
	MonCommandStub        func(context.Context, []byte) ([]byte, string, error)
	monCommandMutex       sync.RWMutex
	monCommandArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	monCommandReturns struct {
		result1 []byte
		result2 string
		result3 error
	}
	monCommandReturnsOnCall map[int]struct {
		result1 []byte
		result2 string
		result3 error
	}
	PoolStub        func(context.Context, string, string) (radosclient.Pool, error)
	poolMutex       sync.RWMutex
	poolArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	poolReturns struct {
		result1 radosclient.Pool
		result2 error
	}
	poolReturnsOnCall map[int]struct {
		result1 radosclient.Pool
		result2 error
	}
	RequiredOSDReleaseStub        func(context.Context) (string, error)
	requiredOSDReleaseMutex       sync.RWMutex
	requiredOSDReleaseArgsForCall []struct {
		arg1 context.Context
	}
	requiredOSDReleaseReturns struct {
		result1 string
		result2 error
	}
	requiredOSDReleaseReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCluster) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeCluster) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeCluster) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ConfigGet(arg1 string) (string, error) {
	fake.configGetMutex.Lock()
	ret, specificReturn := fake.configGetReturnsOnCall[len(fake.configGetArgsForCall)]
	fake.configGetArgsForCall = append(fake.configGetArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ConfigGetStub
	fakeReturns := fake.configGetReturns
	fake.recordInvocation("ConfigGet", []interface{}{arg1})
	fake.configGetMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) ConfigGetCallCount() int {
	fake.configGetMutex.RLock()
	defer fake.configGetMutex.RUnlock()
	return len(fake.configGetArgsForCall)
}

func (fake *FakeCluster) ConfigGetCalls(stub func(string) (string, error)) {
	fake.configGetMutex.Lock()
	defer fake.configGetMutex.Unlock()
	fake.ConfigGetStub = stub
}

func (fake *FakeCluster) ConfigGetArgsForCall(i int) string {
	fake.configGetMutex.RLock()
	defer fake.configGetMutex.RUnlock()
	argsForCall := fake.configGetArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) ConfigGetReturns(result1 string, result2 error) {
	fake.configGetMutex.Lock()
	defer fake.configGetMutex.Unlock()
	fake.ConfigGetStub = nil
	fake.configGetReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) ConfigGetReturnsOnCall(i int, result1 string, result2 error) {
	fake.configGetMutex.Lock()
	defer fake.configGetMutex.Unlock()
	fake.ConfigGetStub = nil
	if fake.configGetReturnsOnCall == nil {
		fake.configGetReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.configGetReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) FSID() (string, error) {
	fake.fSIDMutex.Lock()
	ret, specificReturn := fake.fSIDReturnsOnCall[len(fake.fSIDArgsForCall)]
	fake.fSIDArgsForCall = append(fake.fSIDArgsForCall, struct {
	}{})
	stub := fake.FSIDStub
	fakeReturns := fake.fSIDReturns
	fake.recordInvocation("FSID", []interface{}{})
	fake.fSIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) FSIDCallCount() int {
	fake.fSIDMutex.RLock()
	defer fake.fSIDMutex.RUnlock()
	return len(fake.fSIDArgsForCall)
}

func (fake *FakeCluster) FSIDCalls(stub func() (string, error)) {
	fake.fSIDMutex.Lock()
	defer fake.fSIDMutex.Unlock()
	fake.FSIDStub = stub
}

func (fake *FakeCluster) FSIDReturns(result1 string, result2 error) {
	fake.fSIDMutex.Lock()
	defer fake.fSIDMutex.Unlock()
	fake.FSIDStub = nil
	fake.fSIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) FSIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.fSIDMutex.Lock()
	defer fake.fSIDMutex.Unlock()
	fake.FSIDStub = nil
	if fake.fSIDReturnsOnCall == nil {
		fake.fSIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.fSIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) InstanceID() uint64 {
	fake.instanceIDMutex.Lock()
	ret, specificReturn := fake.instanceIDReturnsOnCall[len(fake.instanceIDArgsForCall)]
	fake.instanceIDArgsForCall = append(fake.instanceIDArgsForCall, struct {
	}{})
	stub := fake.InstanceIDStub
	fakeReturns := fake.instanceIDReturns
	fake.recordInvocation("InstanceID", []interface{}{})
	fake.instanceIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) InstanceIDCallCount() int {
	fake.instanceIDMutex.RLock()
	defer fake.instanceIDMutex.RUnlock()
	return len(fake.instanceIDArgsForCall)
}

func (fake *FakeCluster) InstanceIDCalls(stub func() uint64) {
	fake.instanceIDMutex.Lock()
	defer fake.instanceIDMutex.Unlock()
	fake.InstanceIDStub = stub
}

func (fake *FakeCluster) InstanceIDReturns(result1 uint64) {
	fake.instanceIDMutex.Lock()
	defer fake.instanceIDMutex.Unlock()
	fake.InstanceIDStub = nil
	fake.instanceIDReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) InstanceIDReturnsOnCall(i int, result1 uint64) {
	fake.instanceIDMutex.Lock()
	defer fake.instanceIDMutex.Unlock()
	fake.InstanceIDStub = nil
	if fake.instanceIDReturnsOnCall == nil {
		fake.instanceIDReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.instanceIDReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) MonCommand(arg1 context.Context, arg2 []byte) ([]byte, string, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.monCommandMutex.Lock()
	ret, specificReturn := fake.monCommandReturnsOnCall[len(fake.monCommandArgsForCall)]
	fake.monCommandArgsForCall = append(fake.monCommandArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.MonCommandStub
	fakeReturns := fake.monCommandReturns
	fake.recordInvocation("MonCommand", []interface{}{arg1, arg2Copy})
	fake.monCommandMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCluster) MonCommandCallCount() int {
	fake.monCommandMutex.RLock()
	defer fake.monCommandMutex.RUnlock()
	return len(fake.monCommandArgsForCall)
}

func (fake *FakeCluster) MonCommandCalls(stub func(context.Context, []byte) ([]byte, string, error)) {
	fake.monCommandMutex.Lock()
	defer fake.monCommandMutex.Unlock()
	fake.MonCommandStub = stub
}

func (fake *FakeCluster) MonCommandArgsForCall(i int) (context.Context, []byte) {
	fake.monCommandMutex.RLock()
	defer fake.monCommandMutex.RUnlock()
	argsForCall := fake.monCommandArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) MonCommandReturns(result1 []byte, result2 string, result3 error) {
	fake.monCommandMutex.Lock()
	defer fake.monCommandMutex.Unlock()
	fake.MonCommandStub = nil
	fake.monCommandReturns = struct {
		result1 []byte
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCluster) MonCommandReturnsOnCall(i int, result1 []byte, result2 string, result3 error) {
	fake.monCommandMutex.Lock()
	defer fake.monCommandMutex.Unlock()
	fake.MonCommandStub = nil
	if fake.monCommandReturnsOnCall == nil {
		fake.monCommandReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 string
			result3 error
		})
	}
	fake.monCommandReturnsOnCall[i] = struct {
		result1 []byte
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCluster) Pool(arg1 context.Context, arg2 string, arg3 string) (radosclient.Pool, error) {
	fake.poolMutex.Lock()
	ret, specificReturn := fake.poolReturnsOnCall[len(fake.poolArgsForCall)]
	fake.poolArgsForCall = append(fake.poolArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PoolStub
	fakeReturns := fake.poolReturns
	fake.recordInvocation("Pool", []interface{}{arg1, arg2, arg3})
	fake.poolMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) PoolCallCount() int {
	fake.poolMutex.RLock()
	defer fake.poolMutex.RUnlock()
	return len(fake.poolArgsForCall)
}

func (fake *FakeCluster) PoolCalls(stub func(context.Context, string, string) (radosclient.Pool, error)) {
	fake.poolMutex.Lock()
	defer fake.poolMutex.Unlock()
	fake.PoolStub = stub
}

func (fake *FakeCluster) PoolArgsForCall(i int) (context.Context, string, string) {
	fake.poolMutex.RLock()
	defer fake.poolMutex.RUnlock()
	argsForCall := fake.poolArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCluster) PoolReturns(result1 radosclient.Pool, result2 error) {
	fake.poolMutex.Lock()
	defer fake.poolMutex.Unlock()
	fake.PoolStub = nil
	fake.poolReturns = struct {
		result1 radosclient.Pool
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) PoolReturnsOnCall(i int, result1 radosclient.Pool, result2 error) {
	fake.poolMutex.Lock()
	defer fake.poolMutex.Unlock()
	fake.PoolStub = nil
	if fake.poolReturnsOnCall == nil {
		fake.poolReturnsOnCall = make(map[int]struct {
			result1 radosclient.Pool
			result2 error
		})
	}
	fake.poolReturnsOnCall[i] = struct {
		result1 radosclient.Pool
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) RequiredOSDRelease(arg1 context.Context) (string, error) {
	fake.requiredOSDReleaseMutex.Lock()
	ret, specificReturn := fake.requiredOSDReleaseReturnsOnCall[len(fake.requiredOSDReleaseArgsForCall)]
	fake.requiredOSDReleaseArgsForCall = append(fake.requiredOSDReleaseArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RequiredOSDReleaseStub
	fakeReturns := fake.requiredOSDReleaseReturns
	fake.recordInvocation("RequiredOSDRelease", []interface{}{arg1})
	fake.requiredOSDReleaseMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) RequiredOSDReleaseCallCount() int {
	fake.requiredOSDReleaseMutex.RLock()
	defer fake.requiredOSDReleaseMutex.RUnlock()
	return len(fake.requiredOSDReleaseArgsForCall)
}

func (fake *FakeCluster) RequiredOSDReleaseCalls(stub func(context.Context) (string, error)) {
	fake.requiredOSDReleaseMutex.Lock()
	defer fake.requiredOSDReleaseMutex.Unlock()
	fake.RequiredOSDReleaseStub = stub
}

func (fake *FakeCluster) RequiredOSDReleaseArgsForCall(i int) context.Context {
	fake.requiredOSDReleaseMutex.RLock()
	defer fake.requiredOSDReleaseMutex.RUnlock()
	argsForCall := fake.requiredOSDReleaseArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) RequiredOSDReleaseReturns(result1 string, result2 error) {
	fake.requiredOSDReleaseMutex.Lock()
	defer fake.requiredOSDReleaseMutex.Unlock()
	fake.RequiredOSDReleaseStub = nil
	fake.requiredOSDReleaseReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) RequiredOSDReleaseReturnsOnCall(i int, result1 string, result2 error) {
	fake.requiredOSDReleaseMutex.Lock()
	defer fake.requiredOSDReleaseMutex.Unlock()
	fake.RequiredOSDReleaseStub = nil
	if fake.requiredOSDReleaseReturnsOnCall == nil {
		fake.requiredOSDReleaseReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.requiredOSDReleaseReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCluster) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ radosclient.Cluster = new(FakeCluster)
