// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeBucketAdminStore struct {
	ChangeBucketOwnerStub        func(context.Context, *op.BucketRecord, meta.Owner, string, *meta.BucketID) error
	changeBucketOwnerMutex       sync.RWMutex
	changeBucketOwnerArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
		arg4 string
		arg5 *meta.BucketID
	}
	changeBucketOwnerReturns struct {
		result1 error
	}
	changeBucketOwnerReturnsOnCall map[int]struct {
		result1 error
	}
	CheckIndexStub        func(context.Context, *op.BucketRecord) (map[string]op.CategoryStats, map[string]op.CategoryStats, error)
	checkIndexMutex       sync.RWMutex
	checkIndexArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}
	checkIndexReturns struct {
		result1 map[string]op.CategoryStats
		result2 map[string]op.CategoryStats
		result3 error
	}
	checkIndexReturnsOnCall map[int]struct {
		result1 map[string]op.CategoryStats
		result2 map[string]op.CategoryStats
		result3 error
	}
	ChownBucketStub        func(context.Context, *op.BucketRecord, meta.Owner, string) error
	chownBucketMutex       sync.RWMutex
	chownBucketArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
		arg4 string
	}
	chownBucketReturns struct {
		result1 error
	}
	chownBucketReturnsOnCall map[int]struct {
		result1 error
	}
	IndexStatsStub        func(context.Context, *op.BucketRecord) (op.BucketIndexStats, error)
	indexStatsMutex       sync.RWMutex
	indexStatsArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}
	indexStatsReturns struct {
		result1 op.BucketIndexStats
		result2 error
	}
	indexStatsReturnsOnCall map[int]struct {
		result1 op.BucketIndexStats
		result2 error
	}
	PurgeBypassGCStub        func(context.Context, *op.BucketRecord) error
	purgeBypassGCMutex       sync.RWMutex
	purgeBypassGCArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}
	purgeBypassGCReturns struct {
		result1 error
	}
	purgeBypassGCReturnsOnCall map[int]struct {
		result1 error
	}
	RebuildIndexStub        func(context.Context, *op.BucketRecord) error
	rebuildIndexMutex       sync.RWMutex
	rebuildIndexArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}
	rebuildIndexReturns struct {
		result1 error
	}
	rebuildIndexReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveDanglingEntryPointStub        func(context.Context, string, string) error
	removeDanglingEntryPointMutex       sync.RWMutex
	removeDanglingEntryPointArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	removeDanglingEntryPointReturns struct {
		result1 error
	}
	removeDanglingEntryPointReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveIndexEntriesStub        func(context.Context, *op.BucketRecord, []meta.ObjKey) error
	removeIndexEntriesMutex       sync.RWMutex
	removeIndexEntriesArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 []meta.ObjKey
	}
	removeIndexEntriesReturns struct {
		result1 error
	}
	removeIndexEntriesReturnsOnCall map[int]struct {
		result1 error
	}
	SyncOwnerStatsStub        func(context.Context, meta.Owner) error
	syncOwnerStatsMutex       sync.RWMutex
	syncOwnerStatsArgsForCall []struct {
		arg1 context.Context
		arg2 meta.Owner
	}
	syncOwnerStatsReturns struct {
		result1 error
	}
	syncOwnerStatsReturnsOnCall map[int]struct {
		result1 error
	}
	UnlinkBucketOwnerStub        func(context.Context, *op.BucketRecord, meta.Owner) error
	unlinkBucketOwnerMutex       sync.RWMutex
	unlinkBucketOwnerArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
	}
	unlinkBucketOwnerReturns struct {
		result1 error
	}
	unlinkBucketOwnerReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBucketAdminStore) ChangeBucketOwner(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.Owner, arg4 string, arg5 *meta.BucketID) error {
	fake.changeBucketOwnerMutex.Lock()
	ret, specificReturn := fake.changeBucketOwnerReturnsOnCall[len(fake.changeBucketOwnerArgsForCall)]
	fake.changeBucketOwnerArgsForCall = append(fake.changeBucketOwnerArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
		arg4 string
		arg5 *meta.BucketID
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ChangeBucketOwnerStub
	fakeReturns := fake.changeBucketOwnerReturns
	fake.recordInvocation("ChangeBucketOwner", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.changeBucketOwnerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) ChangeBucketOwnerCallCount() int {
	fake.changeBucketOwnerMutex.RLock()
	defer fake.changeBucketOwnerMutex.RUnlock()
	return len(fake.changeBucketOwnerArgsForCall)
}

func (fake *FakeBucketAdminStore) ChangeBucketOwnerCalls(stub func(context.Context, *op.BucketRecord, meta.Owner, string, *meta.BucketID) error) {
	fake.changeBucketOwnerMutex.Lock()
	defer fake.changeBucketOwnerMutex.Unlock()
	fake.ChangeBucketOwnerStub = stub
}

func (fake *FakeBucketAdminStore) ChangeBucketOwnerArgsForCall(i int) (context.Context, *op.BucketRecord, meta.Owner, string, *meta.BucketID) {
	fake.changeBucketOwnerMutex.RLock()
	defer fake.changeBucketOwnerMutex.RUnlock()
	argsForCall := fake.changeBucketOwnerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeBucketAdminStore) ChangeBucketOwnerReturns(result1 error) {
	fake.changeBucketOwnerMutex.Lock()
	defer fake.changeBucketOwnerMutex.Unlock()
	fake.ChangeBucketOwnerStub = nil
	fake.changeBucketOwnerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) ChangeBucketOwnerReturnsOnCall(i int, result1 error) {
	fake.changeBucketOwnerMutex.Lock()
	defer fake.changeBucketOwnerMutex.Unlock()
	fake.ChangeBucketOwnerStub = nil
	if fake.changeBucketOwnerReturnsOnCall == nil {
		fake.changeBucketOwnerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.changeBucketOwnerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) CheckIndex(arg1 context.Context, arg2 *op.BucketRecord) (map[string]op.CategoryStats, map[string]op.CategoryStats, error) {
	fake.checkIndexMutex.Lock()
	ret, specificReturn := fake.checkIndexReturnsOnCall[len(fake.checkIndexArgsForCall)]
	fake.checkIndexArgsForCall = append(fake.checkIndexArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}{arg1, arg2})
	stub := fake.CheckIndexStub
	fakeReturns := fake.checkIndexReturns
	fake.recordInvocation("CheckIndex", []interface{}{arg1, arg2})
	fake.checkIndexMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeBucketAdminStore) CheckIndexCallCount() int {
	fake.checkIndexMutex.RLock()
	defer fake.checkIndexMutex.RUnlock()
	return len(fake.checkIndexArgsForCall)
}

func (fake *FakeBucketAdminStore) CheckIndexCalls(stub func(context.Context, *op.BucketRecord) (map[string]op.CategoryStats, map[string]op.CategoryStats, error)) {
	fake.checkIndexMutex.Lock()
	defer fake.checkIndexMutex.Unlock()
	fake.CheckIndexStub = stub
}

func (fake *FakeBucketAdminStore) CheckIndexArgsForCall(i int) (context.Context, *op.BucketRecord) {
	fake.checkIndexMutex.RLock()
	defer fake.checkIndexMutex.RUnlock()
	argsForCall := fake.checkIndexArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketAdminStore) CheckIndexReturns(result1 map[string]op.CategoryStats, result2 map[string]op.CategoryStats, result3 error) {
	fake.checkIndexMutex.Lock()
	defer fake.checkIndexMutex.Unlock()
	fake.CheckIndexStub = nil
	fake.checkIndexReturns = struct {
		result1 map[string]op.CategoryStats
		result2 map[string]op.CategoryStats
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeBucketAdminStore) CheckIndexReturnsOnCall(i int, result1 map[string]op.CategoryStats, result2 map[string]op.CategoryStats, result3 error) {
	fake.checkIndexMutex.Lock()
	defer fake.checkIndexMutex.Unlock()
	fake.CheckIndexStub = nil
	if fake.checkIndexReturnsOnCall == nil {
		fake.checkIndexReturnsOnCall = make(map[int]struct {
			result1 map[string]op.CategoryStats
			result2 map[string]op.CategoryStats
			result3 error
		})
	}
	fake.checkIndexReturnsOnCall[i] = struct {
		result1 map[string]op.CategoryStats
		result2 map[string]op.CategoryStats
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeBucketAdminStore) ChownBucket(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.Owner, arg4 string) error {
	fake.chownBucketMutex.Lock()
	ret, specificReturn := fake.chownBucketReturnsOnCall[len(fake.chownBucketArgsForCall)]
	fake.chownBucketArgsForCall = append(fake.chownBucketArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ChownBucketStub
	fakeReturns := fake.chownBucketReturns
	fake.recordInvocation("ChownBucket", []interface{}{arg1, arg2, arg3, arg4})
	fake.chownBucketMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) ChownBucketCallCount() int {
	fake.chownBucketMutex.RLock()
	defer fake.chownBucketMutex.RUnlock()
	return len(fake.chownBucketArgsForCall)
}

func (fake *FakeBucketAdminStore) ChownBucketCalls(stub func(context.Context, *op.BucketRecord, meta.Owner, string) error) {
	fake.chownBucketMutex.Lock()
	defer fake.chownBucketMutex.Unlock()
	fake.ChownBucketStub = stub
}

func (fake *FakeBucketAdminStore) ChownBucketArgsForCall(i int) (context.Context, *op.BucketRecord, meta.Owner, string) {
	fake.chownBucketMutex.RLock()
	defer fake.chownBucketMutex.RUnlock()
	argsForCall := fake.chownBucketArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeBucketAdminStore) ChownBucketReturns(result1 error) {
	fake.chownBucketMutex.Lock()
	defer fake.chownBucketMutex.Unlock()
	fake.ChownBucketStub = nil
	fake.chownBucketReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) ChownBucketReturnsOnCall(i int, result1 error) {
	fake.chownBucketMutex.Lock()
	defer fake.chownBucketMutex.Unlock()
	fake.ChownBucketStub = nil
	if fake.chownBucketReturnsOnCall == nil {
		fake.chownBucketReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.chownBucketReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) IndexStats(arg1 context.Context, arg2 *op.BucketRecord) (op.BucketIndexStats, error) {
	fake.indexStatsMutex.Lock()
	ret, specificReturn := fake.indexStatsReturnsOnCall[len(fake.indexStatsArgsForCall)]
	fake.indexStatsArgsForCall = append(fake.indexStatsArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}{arg1, arg2})
	stub := fake.IndexStatsStub
	fakeReturns := fake.indexStatsReturns
	fake.recordInvocation("IndexStats", []interface{}{arg1, arg2})
	fake.indexStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBucketAdminStore) IndexStatsCallCount() int {
	fake.indexStatsMutex.RLock()
	defer fake.indexStatsMutex.RUnlock()
	return len(fake.indexStatsArgsForCall)
}

func (fake *FakeBucketAdminStore) IndexStatsCalls(stub func(context.Context, *op.BucketRecord) (op.BucketIndexStats, error)) {
	fake.indexStatsMutex.Lock()
	defer fake.indexStatsMutex.Unlock()
	fake.IndexStatsStub = stub
}

func (fake *FakeBucketAdminStore) IndexStatsArgsForCall(i int) (context.Context, *op.BucketRecord) {
	fake.indexStatsMutex.RLock()
	defer fake.indexStatsMutex.RUnlock()
	argsForCall := fake.indexStatsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketAdminStore) IndexStatsReturns(result1 op.BucketIndexStats, result2 error) {
	fake.indexStatsMutex.Lock()
	defer fake.indexStatsMutex.Unlock()
	fake.IndexStatsStub = nil
	fake.indexStatsReturns = struct {
		result1 op.BucketIndexStats
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketAdminStore) IndexStatsReturnsOnCall(i int, result1 op.BucketIndexStats, result2 error) {
	fake.indexStatsMutex.Lock()
	defer fake.indexStatsMutex.Unlock()
	fake.IndexStatsStub = nil
	if fake.indexStatsReturnsOnCall == nil {
		fake.indexStatsReturnsOnCall = make(map[int]struct {
			result1 op.BucketIndexStats
			result2 error
		})
	}
	fake.indexStatsReturnsOnCall[i] = struct {
		result1 op.BucketIndexStats
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketAdminStore) PurgeBypassGC(arg1 context.Context, arg2 *op.BucketRecord) error {
	fake.purgeBypassGCMutex.Lock()
	ret, specificReturn := fake.purgeBypassGCReturnsOnCall[len(fake.purgeBypassGCArgsForCall)]
	fake.purgeBypassGCArgsForCall = append(fake.purgeBypassGCArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}{arg1, arg2})
	stub := fake.PurgeBypassGCStub
	fakeReturns := fake.purgeBypassGCReturns
	fake.recordInvocation("PurgeBypassGC", []interface{}{arg1, arg2})
	fake.purgeBypassGCMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) PurgeBypassGCCallCount() int {
	fake.purgeBypassGCMutex.RLock()
	defer fake.purgeBypassGCMutex.RUnlock()
	return len(fake.purgeBypassGCArgsForCall)
}

func (fake *FakeBucketAdminStore) PurgeBypassGCCalls(stub func(context.Context, *op.BucketRecord) error) {
	fake.purgeBypassGCMutex.Lock()
	defer fake.purgeBypassGCMutex.Unlock()
	fake.PurgeBypassGCStub = stub
}

func (fake *FakeBucketAdminStore) PurgeBypassGCArgsForCall(i int) (context.Context, *op.BucketRecord) {
	fake.purgeBypassGCMutex.RLock()
	defer fake.purgeBypassGCMutex.RUnlock()
	argsForCall := fake.purgeBypassGCArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketAdminStore) PurgeBypassGCReturns(result1 error) {
	fake.purgeBypassGCMutex.Lock()
	defer fake.purgeBypassGCMutex.Unlock()
	fake.PurgeBypassGCStub = nil
	fake.purgeBypassGCReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) PurgeBypassGCReturnsOnCall(i int, result1 error) {
	fake.purgeBypassGCMutex.Lock()
	defer fake.purgeBypassGCMutex.Unlock()
	fake.PurgeBypassGCStub = nil
	if fake.purgeBypassGCReturnsOnCall == nil {
		fake.purgeBypassGCReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.purgeBypassGCReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) RebuildIndex(arg1 context.Context, arg2 *op.BucketRecord) error {
	fake.rebuildIndexMutex.Lock()
	ret, specificReturn := fake.rebuildIndexReturnsOnCall[len(fake.rebuildIndexArgsForCall)]
	fake.rebuildIndexArgsForCall = append(fake.rebuildIndexArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}{arg1, arg2})
	stub := fake.RebuildIndexStub
	fakeReturns := fake.rebuildIndexReturns
	fake.recordInvocation("RebuildIndex", []interface{}{arg1, arg2})
	fake.rebuildIndexMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) RebuildIndexCallCount() int {
	fake.rebuildIndexMutex.RLock()
	defer fake.rebuildIndexMutex.RUnlock()
	return len(fake.rebuildIndexArgsForCall)
}

func (fake *FakeBucketAdminStore) RebuildIndexCalls(stub func(context.Context, *op.BucketRecord) error) {
	fake.rebuildIndexMutex.Lock()
	defer fake.rebuildIndexMutex.Unlock()
	fake.RebuildIndexStub = stub
}

func (fake *FakeBucketAdminStore) RebuildIndexArgsForCall(i int) (context.Context, *op.BucketRecord) {
	fake.rebuildIndexMutex.RLock()
	defer fake.rebuildIndexMutex.RUnlock()
	argsForCall := fake.rebuildIndexArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketAdminStore) RebuildIndexReturns(result1 error) {
	fake.rebuildIndexMutex.Lock()
	defer fake.rebuildIndexMutex.Unlock()
	fake.RebuildIndexStub = nil
	fake.rebuildIndexReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) RebuildIndexReturnsOnCall(i int, result1 error) {
	fake.rebuildIndexMutex.Lock()
	defer fake.rebuildIndexMutex.Unlock()
	fake.RebuildIndexStub = nil
	if fake.rebuildIndexReturnsOnCall == nil {
		fake.rebuildIndexReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.rebuildIndexReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) RemoveDanglingEntryPoint(arg1 context.Context, arg2 string, arg3 string) error {
	fake.removeDanglingEntryPointMutex.Lock()
	ret, specificReturn := fake.removeDanglingEntryPointReturnsOnCall[len(fake.removeDanglingEntryPointArgsForCall)]
	fake.removeDanglingEntryPointArgsForCall = append(fake.removeDanglingEntryPointArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.RemoveDanglingEntryPointStub
	fakeReturns := fake.removeDanglingEntryPointReturns
	fake.recordInvocation("RemoveDanglingEntryPoint", []interface{}{arg1, arg2, arg3})
	fake.removeDanglingEntryPointMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) RemoveDanglingEntryPointCallCount() int {
	fake.removeDanglingEntryPointMutex.RLock()
	defer fake.removeDanglingEntryPointMutex.RUnlock()
	return len(fake.removeDanglingEntryPointArgsForCall)
}

func (fake *FakeBucketAdminStore) RemoveDanglingEntryPointCalls(stub func(context.Context, string, string) error) {
	fake.removeDanglingEntryPointMutex.Lock()
	defer fake.removeDanglingEntryPointMutex.Unlock()
	fake.RemoveDanglingEntryPointStub = stub
}

func (fake *FakeBucketAdminStore) RemoveDanglingEntryPointArgsForCall(i int) (context.Context, string, string) {
	fake.removeDanglingEntryPointMutex.RLock()
	defer fake.removeDanglingEntryPointMutex.RUnlock()
	argsForCall := fake.removeDanglingEntryPointArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBucketAdminStore) RemoveDanglingEntryPointReturns(result1 error) {
	fake.removeDanglingEntryPointMutex.Lock()
	defer fake.removeDanglingEntryPointMutex.Unlock()
	fake.RemoveDanglingEntryPointStub = nil
	fake.removeDanglingEntryPointReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) RemoveDanglingEntryPointReturnsOnCall(i int, result1 error) {
	fake.removeDanglingEntryPointMutex.Lock()
	defer fake.removeDanglingEntryPointMutex.Unlock()
	fake.RemoveDanglingEntryPointStub = nil
	if fake.removeDanglingEntryPointReturnsOnCall == nil {
		fake.removeDanglingEntryPointReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeDanglingEntryPointReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) RemoveIndexEntries(arg1 context.Context, arg2 *op.BucketRecord, arg3 []meta.ObjKey) error {
	var arg3Copy []meta.ObjKey
	if arg3 != nil {
		arg3Copy = make([]meta.ObjKey, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.removeIndexEntriesMutex.Lock()
	ret, specificReturn := fake.removeIndexEntriesReturnsOnCall[len(fake.removeIndexEntriesArgsForCall)]
	fake.removeIndexEntriesArgsForCall = append(fake.removeIndexEntriesArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 []meta.ObjKey
	}{arg1, arg2, arg3Copy})
	stub := fake.RemoveIndexEntriesStub
	fakeReturns := fake.removeIndexEntriesReturns
	fake.recordInvocation("RemoveIndexEntries", []interface{}{arg1, arg2, arg3Copy})
	fake.removeIndexEntriesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) RemoveIndexEntriesCallCount() int {
	fake.removeIndexEntriesMutex.RLock()
	defer fake.removeIndexEntriesMutex.RUnlock()
	return len(fake.removeIndexEntriesArgsForCall)
}

func (fake *FakeBucketAdminStore) RemoveIndexEntriesCalls(stub func(context.Context, *op.BucketRecord, []meta.ObjKey) error) {
	fake.removeIndexEntriesMutex.Lock()
	defer fake.removeIndexEntriesMutex.Unlock()
	fake.RemoveIndexEntriesStub = stub
}

func (fake *FakeBucketAdminStore) RemoveIndexEntriesArgsForCall(i int) (context.Context, *op.BucketRecord, []meta.ObjKey) {
	fake.removeIndexEntriesMutex.RLock()
	defer fake.removeIndexEntriesMutex.RUnlock()
	argsForCall := fake.removeIndexEntriesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBucketAdminStore) RemoveIndexEntriesReturns(result1 error) {
	fake.removeIndexEntriesMutex.Lock()
	defer fake.removeIndexEntriesMutex.Unlock()
	fake.RemoveIndexEntriesStub = nil
	fake.removeIndexEntriesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) RemoveIndexEntriesReturnsOnCall(i int, result1 error) {
	fake.removeIndexEntriesMutex.Lock()
	defer fake.removeIndexEntriesMutex.Unlock()
	fake.RemoveIndexEntriesStub = nil
	if fake.removeIndexEntriesReturnsOnCall == nil {
		fake.removeIndexEntriesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeIndexEntriesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) SyncOwnerStats(arg1 context.Context, arg2 meta.Owner) error {
	fake.syncOwnerStatsMutex.Lock()
	ret, specificReturn := fake.syncOwnerStatsReturnsOnCall[len(fake.syncOwnerStatsArgsForCall)]
	fake.syncOwnerStatsArgsForCall = append(fake.syncOwnerStatsArgsForCall, struct {
		arg1 context.Context
		arg2 meta.Owner
	}{arg1, arg2})
	stub := fake.SyncOwnerStatsStub
	fakeReturns := fake.syncOwnerStatsReturns
	fake.recordInvocation("SyncOwnerStats", []interface{}{arg1, arg2})
	fake.syncOwnerStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) SyncOwnerStatsCallCount() int {
	fake.syncOwnerStatsMutex.RLock()
	defer fake.syncOwnerStatsMutex.RUnlock()
	return len(fake.syncOwnerStatsArgsForCall)
}

func (fake *FakeBucketAdminStore) SyncOwnerStatsCalls(stub func(context.Context, meta.Owner) error) {
	fake.syncOwnerStatsMutex.Lock()
	defer fake.syncOwnerStatsMutex.Unlock()
	fake.SyncOwnerStatsStub = stub
}

func (fake *FakeBucketAdminStore) SyncOwnerStatsArgsForCall(i int) (context.Context, meta.Owner) {
	fake.syncOwnerStatsMutex.RLock()
	defer fake.syncOwnerStatsMutex.RUnlock()
	argsForCall := fake.syncOwnerStatsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketAdminStore) SyncOwnerStatsReturns(result1 error) {
	fake.syncOwnerStatsMutex.Lock()
	defer fake.syncOwnerStatsMutex.Unlock()
	fake.SyncOwnerStatsStub = nil
	fake.syncOwnerStatsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) SyncOwnerStatsReturnsOnCall(i int, result1 error) {
	fake.syncOwnerStatsMutex.Lock()
	defer fake.syncOwnerStatsMutex.Unlock()
	fake.SyncOwnerStatsStub = nil
	if fake.syncOwnerStatsReturnsOnCall == nil {
		fake.syncOwnerStatsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.syncOwnerStatsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) UnlinkBucketOwner(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.Owner) error {
	fake.unlinkBucketOwnerMutex.Lock()
	ret, specificReturn := fake.unlinkBucketOwnerReturnsOnCall[len(fake.unlinkBucketOwnerArgsForCall)]
	fake.unlinkBucketOwnerArgsForCall = append(fake.unlinkBucketOwnerArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
	}{arg1, arg2, arg3})
	stub := fake.UnlinkBucketOwnerStub
	fakeReturns := fake.unlinkBucketOwnerReturns
	fake.recordInvocation("UnlinkBucketOwner", []interface{}{arg1, arg2, arg3})
	fake.unlinkBucketOwnerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketAdminStore) UnlinkBucketOwnerCallCount() int {
	fake.unlinkBucketOwnerMutex.RLock()
	defer fake.unlinkBucketOwnerMutex.RUnlock()
	return len(fake.unlinkBucketOwnerArgsForCall)
}

func (fake *FakeBucketAdminStore) UnlinkBucketOwnerCalls(stub func(context.Context, *op.BucketRecord, meta.Owner) error) {
	fake.unlinkBucketOwnerMutex.Lock()
	defer fake.unlinkBucketOwnerMutex.Unlock()
	fake.UnlinkBucketOwnerStub = stub
}

func (fake *FakeBucketAdminStore) UnlinkBucketOwnerArgsForCall(i int) (context.Context, *op.BucketRecord, meta.Owner) {
	fake.unlinkBucketOwnerMutex.RLock()
	defer fake.unlinkBucketOwnerMutex.RUnlock()
	argsForCall := fake.unlinkBucketOwnerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBucketAdminStore) UnlinkBucketOwnerReturns(result1 error) {
	fake.unlinkBucketOwnerMutex.Lock()
	defer fake.unlinkBucketOwnerMutex.Unlock()
	fake.UnlinkBucketOwnerStub = nil
	fake.unlinkBucketOwnerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) UnlinkBucketOwnerReturnsOnCall(i int, result1 error) {
	fake.unlinkBucketOwnerMutex.Lock()
	defer fake.unlinkBucketOwnerMutex.Unlock()
	fake.UnlinkBucketOwnerStub = nil
	if fake.unlinkBucketOwnerReturnsOnCall == nil {
		fake.unlinkBucketOwnerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unlinkBucketOwnerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketAdminStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBucketAdminStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.BucketAdminStore = new(FakeBucketAdminStore)
