// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"io"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeMultipartStore struct {
	AbortStub        func(context.Context, *op.Upload) error
	abortMutex       sync.RWMutex
	abortArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Upload
	}
	abortReturns struct {
		result1 error
	}
	abortReturnsOnCall map[int]struct {
		result1 error
	}
	CompleteStub        func(context.Context, *op.Upload, []op.CompletePart) (*op.PutResult, error)
	completeMutex       sync.RWMutex
	completeArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 []op.CompletePart
	}
	completeReturns struct {
		result1 *op.PutResult
		result2 error
	}
	completeReturnsOnCall map[int]struct {
		result1 *op.PutResult
		result2 error
	}
	CopyPartStub        func(context.Context, *op.Upload, int, *op.ObjectState, op.ByteRange) (*op.PartResult, error)
	copyPartMutex       sync.RWMutex
	copyPartArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 int
		arg4 *op.ObjectState
		arg5 op.ByteRange
	}
	copyPartReturns struct {
		result1 *op.PartResult
		result2 error
	}
	copyPartReturnsOnCall map[int]struct {
		result1 *op.PartResult
		result2 error
	}
	CreateUploadStub        func(context.Context, *op.BucketRecord, meta.ObjKey, op.UploadParams) (*op.Upload, error)
	createUploadMutex       sync.RWMutex
	createUploadArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 op.UploadParams
	}
	createUploadReturns struct {
		result1 *op.Upload
		result2 error
	}
	createUploadReturnsOnCall map[int]struct {
		result1 *op.Upload
		result2 error
	}
	GetUploadStub        func(context.Context, *op.BucketRecord, meta.ObjKey, string) (*op.Upload, error)
	getUploadMutex       sync.RWMutex
	getUploadArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 string
	}
	getUploadReturns struct {
		result1 *op.Upload
		result2 error
	}
	getUploadReturnsOnCall map[int]struct {
		result1 *op.Upload
		result2 error
	}
	ListPartsStub        func(context.Context, *op.Upload, int, int) (op.ListPartsResult, error)
	listPartsMutex       sync.RWMutex
	listPartsArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 int
		arg4 int
	}
	listPartsReturns struct {
		result1 op.ListPartsResult
		result2 error
	}
	listPartsReturnsOnCall map[int]struct {
		result1 op.ListPartsResult
		result2 error
	}
	ListUploadsStub        func(context.Context, *op.BucketRecord, op.ListUploadsParams) (op.ListUploadsResult, error)
	listUploadsMutex       sync.RWMutex
	listUploadsArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 op.ListUploadsParams
	}
	listUploadsReturns struct {
		result1 op.ListUploadsResult
		result2 error
	}
	listUploadsReturnsOnCall map[int]struct {
		result1 op.ListUploadsResult
		result2 error
	}
	PutPartStub        func(context.Context, *op.Upload, int, io.Reader, op.PutParams) (*op.PartResult, error)
	putPartMutex       sync.RWMutex
	putPartArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 int
		arg4 io.Reader
		arg5 op.PutParams
	}
	putPartReturns struct {
		result1 *op.PartResult
		result2 error
	}
	putPartReturnsOnCall map[int]struct {
		result1 *op.PartResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMultipartStore) Abort(arg1 context.Context, arg2 *op.Upload) error {
	fake.abortMutex.Lock()
	ret, specificReturn := fake.abortReturnsOnCall[len(fake.abortArgsForCall)]
	fake.abortArgsForCall = append(fake.abortArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Upload
	}{arg1, arg2})
	stub := fake.AbortStub
	fakeReturns := fake.abortReturns
	fake.recordInvocation("Abort", []interface{}{arg1, arg2})
	fake.abortMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMultipartStore) AbortCallCount() int {
	fake.abortMutex.RLock()
	defer fake.abortMutex.RUnlock()
	return len(fake.abortArgsForCall)
}

func (fake *FakeMultipartStore) AbortCalls(stub func(context.Context, *op.Upload) error) {
	fake.abortMutex.Lock()
	defer fake.abortMutex.Unlock()
	fake.AbortStub = stub
}

func (fake *FakeMultipartStore) AbortArgsForCall(i int) (context.Context, *op.Upload) {
	fake.abortMutex.RLock()
	defer fake.abortMutex.RUnlock()
	argsForCall := fake.abortArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMultipartStore) AbortReturns(result1 error) {
	fake.abortMutex.Lock()
	defer fake.abortMutex.Unlock()
	fake.AbortStub = nil
	fake.abortReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMultipartStore) AbortReturnsOnCall(i int, result1 error) {
	fake.abortMutex.Lock()
	defer fake.abortMutex.Unlock()
	fake.AbortStub = nil
	if fake.abortReturnsOnCall == nil {
		fake.abortReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.abortReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMultipartStore) Complete(arg1 context.Context, arg2 *op.Upload, arg3 []op.CompletePart) (*op.PutResult, error) {
	var arg3Copy []op.CompletePart
	if arg3 != nil {
		arg3Copy = make([]op.CompletePart, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.completeMutex.Lock()
	ret, specificReturn := fake.completeReturnsOnCall[len(fake.completeArgsForCall)]
	fake.completeArgsForCall = append(fake.completeArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 []op.CompletePart
	}{arg1, arg2, arg3Copy})
	stub := fake.CompleteStub
	fakeReturns := fake.completeReturns
	fake.recordInvocation("Complete", []interface{}{arg1, arg2, arg3Copy})
	fake.completeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultipartStore) CompleteCallCount() int {
	fake.completeMutex.RLock()
	defer fake.completeMutex.RUnlock()
	return len(fake.completeArgsForCall)
}

func (fake *FakeMultipartStore) CompleteCalls(stub func(context.Context, *op.Upload, []op.CompletePart) (*op.PutResult, error)) {
	fake.completeMutex.Lock()
	defer fake.completeMutex.Unlock()
	fake.CompleteStub = stub
}

func (fake *FakeMultipartStore) CompleteArgsForCall(i int) (context.Context, *op.Upload, []op.CompletePart) {
	fake.completeMutex.RLock()
	defer fake.completeMutex.RUnlock()
	argsForCall := fake.completeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMultipartStore) CompleteReturns(result1 *op.PutResult, result2 error) {
	fake.completeMutex.Lock()
	defer fake.completeMutex.Unlock()
	fake.CompleteStub = nil
	fake.completeReturns = struct {
		result1 *op.PutResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) CompleteReturnsOnCall(i int, result1 *op.PutResult, result2 error) {
	fake.completeMutex.Lock()
	defer fake.completeMutex.Unlock()
	fake.CompleteStub = nil
	if fake.completeReturnsOnCall == nil {
		fake.completeReturnsOnCall = make(map[int]struct {
			result1 *op.PutResult
			result2 error
		})
	}
	fake.completeReturnsOnCall[i] = struct {
		result1 *op.PutResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) CopyPart(arg1 context.Context, arg2 *op.Upload, arg3 int, arg4 *op.ObjectState, arg5 op.ByteRange) (*op.PartResult, error) {
	fake.copyPartMutex.Lock()
	ret, specificReturn := fake.copyPartReturnsOnCall[len(fake.copyPartArgsForCall)]
	fake.copyPartArgsForCall = append(fake.copyPartArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 int
		arg4 *op.ObjectState
		arg5 op.ByteRange
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.CopyPartStub
	fakeReturns := fake.copyPartReturns
	fake.recordInvocation("CopyPart", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.copyPartMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultipartStore) CopyPartCallCount() int {
	fake.copyPartMutex.RLock()
	defer fake.copyPartMutex.RUnlock()
	return len(fake.copyPartArgsForCall)
}

func (fake *FakeMultipartStore) CopyPartCalls(stub func(context.Context, *op.Upload, int, *op.ObjectState, op.ByteRange) (*op.PartResult, error)) {
	fake.copyPartMutex.Lock()
	defer fake.copyPartMutex.Unlock()
	fake.CopyPartStub = stub
}

func (fake *FakeMultipartStore) CopyPartArgsForCall(i int) (context.Context, *op.Upload, int, *op.ObjectState, op.ByteRange) {
	fake.copyPartMutex.RLock()
	defer fake.copyPartMutex.RUnlock()
	argsForCall := fake.copyPartArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeMultipartStore) CopyPartReturns(result1 *op.PartResult, result2 error) {
	fake.copyPartMutex.Lock()
	defer fake.copyPartMutex.Unlock()
	fake.CopyPartStub = nil
	fake.copyPartReturns = struct {
		result1 *op.PartResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) CopyPartReturnsOnCall(i int, result1 *op.PartResult, result2 error) {
	fake.copyPartMutex.Lock()
	defer fake.copyPartMutex.Unlock()
	fake.CopyPartStub = nil
	if fake.copyPartReturnsOnCall == nil {
		fake.copyPartReturnsOnCall = make(map[int]struct {
			result1 *op.PartResult
			result2 error
		})
	}
	fake.copyPartReturnsOnCall[i] = struct {
		result1 *op.PartResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) CreateUpload(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.ObjKey, arg4 op.UploadParams) (*op.Upload, error) {
	fake.createUploadMutex.Lock()
	ret, specificReturn := fake.createUploadReturnsOnCall[len(fake.createUploadArgsForCall)]
	fake.createUploadArgsForCall = append(fake.createUploadArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 op.UploadParams
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreateUploadStub
	fakeReturns := fake.createUploadReturns
	fake.recordInvocation("CreateUpload", []interface{}{arg1, arg2, arg3, arg4})
	fake.createUploadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultipartStore) CreateUploadCallCount() int {
	fake.createUploadMutex.RLock()
	defer fake.createUploadMutex.RUnlock()
	return len(fake.createUploadArgsForCall)
}

func (fake *FakeMultipartStore) CreateUploadCalls(stub func(context.Context, *op.BucketRecord, meta.ObjKey, op.UploadParams) (*op.Upload, error)) {
	fake.createUploadMutex.Lock()
	defer fake.createUploadMutex.Unlock()
	fake.CreateUploadStub = stub
}

func (fake *FakeMultipartStore) CreateUploadArgsForCall(i int) (context.Context, *op.BucketRecord, meta.ObjKey, op.UploadParams) {
	fake.createUploadMutex.RLock()
	defer fake.createUploadMutex.RUnlock()
	argsForCall := fake.createUploadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMultipartStore) CreateUploadReturns(result1 *op.Upload, result2 error) {
	fake.createUploadMutex.Lock()
	defer fake.createUploadMutex.Unlock()
	fake.CreateUploadStub = nil
	fake.createUploadReturns = struct {
		result1 *op.Upload
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) CreateUploadReturnsOnCall(i int, result1 *op.Upload, result2 error) {
	fake.createUploadMutex.Lock()
	defer fake.createUploadMutex.Unlock()
	fake.CreateUploadStub = nil
	if fake.createUploadReturnsOnCall == nil {
		fake.createUploadReturnsOnCall = make(map[int]struct {
			result1 *op.Upload
			result2 error
		})
	}
	fake.createUploadReturnsOnCall[i] = struct {
		result1 *op.Upload
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) GetUpload(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.ObjKey, arg4 string) (*op.Upload, error) {
	fake.getUploadMutex.Lock()
	ret, specificReturn := fake.getUploadReturnsOnCall[len(fake.getUploadArgsForCall)]
	fake.getUploadArgsForCall = append(fake.getUploadArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetUploadStub
	fakeReturns := fake.getUploadReturns
	fake.recordInvocation("GetUpload", []interface{}{arg1, arg2, arg3, arg4})
	fake.getUploadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultipartStore) GetUploadCallCount() int {
	fake.getUploadMutex.RLock()
	defer fake.getUploadMutex.RUnlock()
	return len(fake.getUploadArgsForCall)
}

func (fake *FakeMultipartStore) GetUploadCalls(stub func(context.Context, *op.BucketRecord, meta.ObjKey, string) (*op.Upload, error)) {
	fake.getUploadMutex.Lock()
	defer fake.getUploadMutex.Unlock()
	fake.GetUploadStub = stub
}

func (fake *FakeMultipartStore) GetUploadArgsForCall(i int) (context.Context, *op.BucketRecord, meta.ObjKey, string) {
	fake.getUploadMutex.RLock()
	defer fake.getUploadMutex.RUnlock()
	argsForCall := fake.getUploadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMultipartStore) GetUploadReturns(result1 *op.Upload, result2 error) {
	fake.getUploadMutex.Lock()
	defer fake.getUploadMutex.Unlock()
	fake.GetUploadStub = nil
	fake.getUploadReturns = struct {
		result1 *op.Upload
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) GetUploadReturnsOnCall(i int, result1 *op.Upload, result2 error) {
	fake.getUploadMutex.Lock()
	defer fake.getUploadMutex.Unlock()
	fake.GetUploadStub = nil
	if fake.getUploadReturnsOnCall == nil {
		fake.getUploadReturnsOnCall = make(map[int]struct {
			result1 *op.Upload
			result2 error
		})
	}
	fake.getUploadReturnsOnCall[i] = struct {
		result1 *op.Upload
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) ListParts(arg1 context.Context, arg2 *op.Upload, arg3 int, arg4 int) (op.ListPartsResult, error) {
	fake.listPartsMutex.Lock()
	ret, specificReturn := fake.listPartsReturnsOnCall[len(fake.listPartsArgsForCall)]
	fake.listPartsArgsForCall = append(fake.listPartsArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListPartsStub
	fakeReturns := fake.listPartsReturns
	fake.recordInvocation("ListParts", []interface{}{arg1, arg2, arg3, arg4})
	fake.listPartsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultipartStore) ListPartsCallCount() int {
	fake.listPartsMutex.RLock()
	defer fake.listPartsMutex.RUnlock()
	return len(fake.listPartsArgsForCall)
}

func (fake *FakeMultipartStore) ListPartsCalls(stub func(context.Context, *op.Upload, int, int) (op.ListPartsResult, error)) {
	fake.listPartsMutex.Lock()
	defer fake.listPartsMutex.Unlock()
	fake.ListPartsStub = stub
}

func (fake *FakeMultipartStore) ListPartsArgsForCall(i int) (context.Context, *op.Upload, int, int) {
	fake.listPartsMutex.RLock()
	defer fake.listPartsMutex.RUnlock()
	argsForCall := fake.listPartsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMultipartStore) ListPartsReturns(result1 op.ListPartsResult, result2 error) {
	fake.listPartsMutex.Lock()
	defer fake.listPartsMutex.Unlock()
	fake.ListPartsStub = nil
	fake.listPartsReturns = struct {
		result1 op.ListPartsResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) ListPartsReturnsOnCall(i int, result1 op.ListPartsResult, result2 error) {
	fake.listPartsMutex.Lock()
	defer fake.listPartsMutex.Unlock()
	fake.ListPartsStub = nil
	if fake.listPartsReturnsOnCall == nil {
		fake.listPartsReturnsOnCall = make(map[int]struct {
			result1 op.ListPartsResult
			result2 error
		})
	}
	fake.listPartsReturnsOnCall[i] = struct {
		result1 op.ListPartsResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) ListUploads(arg1 context.Context, arg2 *op.BucketRecord, arg3 op.ListUploadsParams) (op.ListUploadsResult, error) {
	fake.listUploadsMutex.Lock()
	ret, specificReturn := fake.listUploadsReturnsOnCall[len(fake.listUploadsArgsForCall)]
	fake.listUploadsArgsForCall = append(fake.listUploadsArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 op.ListUploadsParams
	}{arg1, arg2, arg3})
	stub := fake.ListUploadsStub
	fakeReturns := fake.listUploadsReturns
	fake.recordInvocation("ListUploads", []interface{}{arg1, arg2, arg3})
	fake.listUploadsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultipartStore) ListUploadsCallCount() int {
	fake.listUploadsMutex.RLock()
	defer fake.listUploadsMutex.RUnlock()
	return len(fake.listUploadsArgsForCall)
}

func (fake *FakeMultipartStore) ListUploadsCalls(stub func(context.Context, *op.BucketRecord, op.ListUploadsParams) (op.ListUploadsResult, error)) {
	fake.listUploadsMutex.Lock()
	defer fake.listUploadsMutex.Unlock()
	fake.ListUploadsStub = stub
}

func (fake *FakeMultipartStore) ListUploadsArgsForCall(i int) (context.Context, *op.BucketRecord, op.ListUploadsParams) {
	fake.listUploadsMutex.RLock()
	defer fake.listUploadsMutex.RUnlock()
	argsForCall := fake.listUploadsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMultipartStore) ListUploadsReturns(result1 op.ListUploadsResult, result2 error) {
	fake.listUploadsMutex.Lock()
	defer fake.listUploadsMutex.Unlock()
	fake.ListUploadsStub = nil
	fake.listUploadsReturns = struct {
		result1 op.ListUploadsResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) ListUploadsReturnsOnCall(i int, result1 op.ListUploadsResult, result2 error) {
	fake.listUploadsMutex.Lock()
	defer fake.listUploadsMutex.Unlock()
	fake.ListUploadsStub = nil
	if fake.listUploadsReturnsOnCall == nil {
		fake.listUploadsReturnsOnCall = make(map[int]struct {
			result1 op.ListUploadsResult
			result2 error
		})
	}
	fake.listUploadsReturnsOnCall[i] = struct {
		result1 op.ListUploadsResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) PutPart(arg1 context.Context, arg2 *op.Upload, arg3 int, arg4 io.Reader, arg5 op.PutParams) (*op.PartResult, error) {
	fake.putPartMutex.Lock()
	ret, specificReturn := fake.putPartReturnsOnCall[len(fake.putPartArgsForCall)]
	fake.putPartArgsForCall = append(fake.putPartArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Upload
		arg3 int
		arg4 io.Reader
		arg5 op.PutParams
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PutPartStub
	fakeReturns := fake.putPartReturns
	fake.recordInvocation("PutPart", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.putPartMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultipartStore) PutPartCallCount() int {
	fake.putPartMutex.RLock()
	defer fake.putPartMutex.RUnlock()
	return len(fake.putPartArgsForCall)
}

func (fake *FakeMultipartStore) PutPartCalls(stub func(context.Context, *op.Upload, int, io.Reader, op.PutParams) (*op.PartResult, error)) {
	fake.putPartMutex.Lock()
	defer fake.putPartMutex.Unlock()
	fake.PutPartStub = stub
}

func (fake *FakeMultipartStore) PutPartArgsForCall(i int) (context.Context, *op.Upload, int, io.Reader, op.PutParams) {
	fake.putPartMutex.RLock()
	defer fake.putPartMutex.RUnlock()
	argsForCall := fake.putPartArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeMultipartStore) PutPartReturns(result1 *op.PartResult, result2 error) {
	fake.putPartMutex.Lock()
	defer fake.putPartMutex.Unlock()
	fake.PutPartStub = nil
	fake.putPartReturns = struct {
		result1 *op.PartResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) PutPartReturnsOnCall(i int, result1 *op.PartResult, result2 error) {
	fake.putPartMutex.Lock()
	defer fake.putPartMutex.Unlock()
	fake.PutPartStub = nil
	if fake.putPartReturnsOnCall == nil {
		fake.putPartReturnsOnCall = make(map[int]struct {
			result1 *op.PartResult
			result2 error
		})
	}
	fake.putPartReturnsOnCall[i] = struct {
		result1 *op.PartResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMultipartStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMultipartStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.MultipartStore = new(FakeMultipartStore)
