// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeUsageLogger struct {
	LogStub        func(context.Context, op.UsageEntry)
	logMutex       sync.RWMutex
	logArgsForCall []struct {
		arg1 context.Context
		arg2 op.UsageEntry
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUsageLogger) Log(arg1 context.Context, arg2 op.UsageEntry) {
	fake.logMutex.Lock()
	fake.logArgsForCall = append(fake.logArgsForCall, struct {
		arg1 context.Context
		arg2 op.UsageEntry
	}{arg1, arg2})
	stub := fake.LogStub
	fake.recordInvocation("Log", []interface{}{arg1, arg2})
	fake.logMutex.Unlock()
	if stub != nil {
		fake.LogStub(arg1, arg2)
	}
}

func (fake *FakeUsageLogger) LogCallCount() int {
	fake.logMutex.RLock()
	defer fake.logMutex.RUnlock()
	return len(fake.logArgsForCall)
}

func (fake *FakeUsageLogger) LogCalls(stub func(context.Context, op.UsageEntry)) {
	fake.logMutex.Lock()
	defer fake.logMutex.Unlock()
	fake.LogStub = stub
}

func (fake *FakeUsageLogger) LogArgsForCall(i int) (context.Context, op.UsageEntry) {
	fake.logMutex.RLock()
	defer fake.logMutex.RUnlock()
	argsForCall := fake.logArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUsageLogger) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUsageLogger) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.UsageLogger = new(FakeUsageLogger)
