// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeBucketStore struct {
	CreateBucketStub        func(context.Context, op.CreateBucketParams) (*op.BucketRecord, error)
	createBucketMutex       sync.RWMutex
	createBucketArgsForCall []struct {
		arg1 context.Context
		arg2 op.CreateBucketParams
	}
	createBucketReturns struct {
		result1 *op.BucketRecord
		result2 error
	}
	createBucketReturnsOnCall map[int]struct {
		result1 *op.BucketRecord
		result2 error
	}
	DeleteBucketStub        func(context.Context, *op.BucketRecord) error
	deleteBucketMutex       sync.RWMutex
	deleteBucketArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}
	deleteBucketReturns struct {
		result1 error
	}
	deleteBucketReturnsOnCall map[int]struct {
		result1 error
	}
	GetBucketStub        func(context.Context, string, string) (*op.BucketRecord, error)
	getBucketMutex       sync.RWMutex
	getBucketArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getBucketReturns struct {
		result1 *op.BucketRecord
		result2 error
	}
	getBucketReturnsOnCall map[int]struct {
		result1 *op.BucketRecord
		result2 error
	}
	GetBucketInstanceStub        func(context.Context, meta.BucketID) (*op.BucketRecord, error)
	getBucketInstanceMutex       sync.RWMutex
	getBucketInstanceArgsForCall []struct {
		arg1 context.Context
		arg2 meta.BucketID
	}
	getBucketInstanceReturns struct {
		result1 *op.BucketRecord
		result2 error
	}
	getBucketInstanceReturnsOnCall map[int]struct {
		result1 *op.BucketRecord
		result2 error
	}
	ListObjectsStub        func(context.Context, *op.BucketRecord, op.ListObjectsParams) (op.ListObjectsResult, error)
	listObjectsMutex       sync.RWMutex
	listObjectsArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 op.ListObjectsParams
	}
	listObjectsReturns struct {
		result1 op.ListObjectsResult
		result2 error
	}
	listObjectsReturnsOnCall map[int]struct {
		result1 op.ListObjectsResult
		result2 error
	}
	PutBucketAttrsStub        func(context.Context, *op.BucketRecord, map[string][]byte, []string) error
	putBucketAttrsMutex       sync.RWMutex
	putBucketAttrsArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 map[string][]byte
		arg4 []string
	}
	putBucketAttrsReturns struct {
		result1 error
	}
	putBucketAttrsReturnsOnCall map[int]struct {
		result1 error
	}
	PutBucketInfoStub        func(context.Context, *op.BucketRecord) error
	putBucketInfoMutex       sync.RWMutex
	putBucketInfoArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}
	putBucketInfoReturns struct {
		result1 error
	}
	putBucketInfoReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBucketStore) CreateBucket(arg1 context.Context, arg2 op.CreateBucketParams) (*op.BucketRecord, error) {
	fake.createBucketMutex.Lock()
	ret, specificReturn := fake.createBucketReturnsOnCall[len(fake.createBucketArgsForCall)]
	fake.createBucketArgsForCall = append(fake.createBucketArgsForCall, struct {
		arg1 context.Context
		arg2 op.CreateBucketParams
	}{arg1, arg2})
	stub := fake.CreateBucketStub
	fakeReturns := fake.createBucketReturns
	fake.recordInvocation("CreateBucket", []interface{}{arg1, arg2})
	fake.createBucketMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBucketStore) CreateBucketCallCount() int {
	fake.createBucketMutex.RLock()
	defer fake.createBucketMutex.RUnlock()
	return len(fake.createBucketArgsForCall)
}

func (fake *FakeBucketStore) CreateBucketCalls(stub func(context.Context, op.CreateBucketParams) (*op.BucketRecord, error)) {
	fake.createBucketMutex.Lock()
	defer fake.createBucketMutex.Unlock()
	fake.CreateBucketStub = stub
}

func (fake *FakeBucketStore) CreateBucketArgsForCall(i int) (context.Context, op.CreateBucketParams) {
	fake.createBucketMutex.RLock()
	defer fake.createBucketMutex.RUnlock()
	argsForCall := fake.createBucketArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketStore) CreateBucketReturns(result1 *op.BucketRecord, result2 error) {
	fake.createBucketMutex.Lock()
	defer fake.createBucketMutex.Unlock()
	fake.CreateBucketStub = nil
	fake.createBucketReturns = struct {
		result1 *op.BucketRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) CreateBucketReturnsOnCall(i int, result1 *op.BucketRecord, result2 error) {
	fake.createBucketMutex.Lock()
	defer fake.createBucketMutex.Unlock()
	fake.CreateBucketStub = nil
	if fake.createBucketReturnsOnCall == nil {
		fake.createBucketReturnsOnCall = make(map[int]struct {
			result1 *op.BucketRecord
			result2 error
		})
	}
	fake.createBucketReturnsOnCall[i] = struct {
		result1 *op.BucketRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) DeleteBucket(arg1 context.Context, arg2 *op.BucketRecord) error {
	fake.deleteBucketMutex.Lock()
	ret, specificReturn := fake.deleteBucketReturnsOnCall[len(fake.deleteBucketArgsForCall)]
	fake.deleteBucketArgsForCall = append(fake.deleteBucketArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}{arg1, arg2})
	stub := fake.DeleteBucketStub
	fakeReturns := fake.deleteBucketReturns
	fake.recordInvocation("DeleteBucket", []interface{}{arg1, arg2})
	fake.deleteBucketMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketStore) DeleteBucketCallCount() int {
	fake.deleteBucketMutex.RLock()
	defer fake.deleteBucketMutex.RUnlock()
	return len(fake.deleteBucketArgsForCall)
}

func (fake *FakeBucketStore) DeleteBucketCalls(stub func(context.Context, *op.BucketRecord) error) {
	fake.deleteBucketMutex.Lock()
	defer fake.deleteBucketMutex.Unlock()
	fake.DeleteBucketStub = stub
}

func (fake *FakeBucketStore) DeleteBucketArgsForCall(i int) (context.Context, *op.BucketRecord) {
	fake.deleteBucketMutex.RLock()
	defer fake.deleteBucketMutex.RUnlock()
	argsForCall := fake.deleteBucketArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketStore) DeleteBucketReturns(result1 error) {
	fake.deleteBucketMutex.Lock()
	defer fake.deleteBucketMutex.Unlock()
	fake.DeleteBucketStub = nil
	fake.deleteBucketReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketStore) DeleteBucketReturnsOnCall(i int, result1 error) {
	fake.deleteBucketMutex.Lock()
	defer fake.deleteBucketMutex.Unlock()
	fake.DeleteBucketStub = nil
	if fake.deleteBucketReturnsOnCall == nil {
		fake.deleteBucketReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteBucketReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketStore) GetBucket(arg1 context.Context, arg2 string, arg3 string) (*op.BucketRecord, error) {
	fake.getBucketMutex.Lock()
	ret, specificReturn := fake.getBucketReturnsOnCall[len(fake.getBucketArgsForCall)]
	fake.getBucketArgsForCall = append(fake.getBucketArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetBucketStub
	fakeReturns := fake.getBucketReturns
	fake.recordInvocation("GetBucket", []interface{}{arg1, arg2, arg3})
	fake.getBucketMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBucketStore) GetBucketCallCount() int {
	fake.getBucketMutex.RLock()
	defer fake.getBucketMutex.RUnlock()
	return len(fake.getBucketArgsForCall)
}

func (fake *FakeBucketStore) GetBucketCalls(stub func(context.Context, string, string) (*op.BucketRecord, error)) {
	fake.getBucketMutex.Lock()
	defer fake.getBucketMutex.Unlock()
	fake.GetBucketStub = stub
}

func (fake *FakeBucketStore) GetBucketArgsForCall(i int) (context.Context, string, string) {
	fake.getBucketMutex.RLock()
	defer fake.getBucketMutex.RUnlock()
	argsForCall := fake.getBucketArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBucketStore) GetBucketReturns(result1 *op.BucketRecord, result2 error) {
	fake.getBucketMutex.Lock()
	defer fake.getBucketMutex.Unlock()
	fake.GetBucketStub = nil
	fake.getBucketReturns = struct {
		result1 *op.BucketRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) GetBucketReturnsOnCall(i int, result1 *op.BucketRecord, result2 error) {
	fake.getBucketMutex.Lock()
	defer fake.getBucketMutex.Unlock()
	fake.GetBucketStub = nil
	if fake.getBucketReturnsOnCall == nil {
		fake.getBucketReturnsOnCall = make(map[int]struct {
			result1 *op.BucketRecord
			result2 error
		})
	}
	fake.getBucketReturnsOnCall[i] = struct {
		result1 *op.BucketRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) GetBucketInstance(arg1 context.Context, arg2 meta.BucketID) (*op.BucketRecord, error) {
	fake.getBucketInstanceMutex.Lock()
	ret, specificReturn := fake.getBucketInstanceReturnsOnCall[len(fake.getBucketInstanceArgsForCall)]
	fake.getBucketInstanceArgsForCall = append(fake.getBucketInstanceArgsForCall, struct {
		arg1 context.Context
		arg2 meta.BucketID
	}{arg1, arg2})
	stub := fake.GetBucketInstanceStub
	fakeReturns := fake.getBucketInstanceReturns
	fake.recordInvocation("GetBucketInstance", []interface{}{arg1, arg2})
	fake.getBucketInstanceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBucketStore) GetBucketInstanceCallCount() int {
	fake.getBucketInstanceMutex.RLock()
	defer fake.getBucketInstanceMutex.RUnlock()
	return len(fake.getBucketInstanceArgsForCall)
}

func (fake *FakeBucketStore) GetBucketInstanceCalls(stub func(context.Context, meta.BucketID) (*op.BucketRecord, error)) {
	fake.getBucketInstanceMutex.Lock()
	defer fake.getBucketInstanceMutex.Unlock()
	fake.GetBucketInstanceStub = stub
}

func (fake *FakeBucketStore) GetBucketInstanceArgsForCall(i int) (context.Context, meta.BucketID) {
	fake.getBucketInstanceMutex.RLock()
	defer fake.getBucketInstanceMutex.RUnlock()
	argsForCall := fake.getBucketInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketStore) GetBucketInstanceReturns(result1 *op.BucketRecord, result2 error) {
	fake.getBucketInstanceMutex.Lock()
	defer fake.getBucketInstanceMutex.Unlock()
	fake.GetBucketInstanceStub = nil
	fake.getBucketInstanceReturns = struct {
		result1 *op.BucketRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) GetBucketInstanceReturnsOnCall(i int, result1 *op.BucketRecord, result2 error) {
	fake.getBucketInstanceMutex.Lock()
	defer fake.getBucketInstanceMutex.Unlock()
	fake.GetBucketInstanceStub = nil
	if fake.getBucketInstanceReturnsOnCall == nil {
		fake.getBucketInstanceReturnsOnCall = make(map[int]struct {
			result1 *op.BucketRecord
			result2 error
		})
	}
	fake.getBucketInstanceReturnsOnCall[i] = struct {
		result1 *op.BucketRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) ListObjects(arg1 context.Context, arg2 *op.BucketRecord, arg3 op.ListObjectsParams) (op.ListObjectsResult, error) {
	fake.listObjectsMutex.Lock()
	ret, specificReturn := fake.listObjectsReturnsOnCall[len(fake.listObjectsArgsForCall)]
	fake.listObjectsArgsForCall = append(fake.listObjectsArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 op.ListObjectsParams
	}{arg1, arg2, arg3})
	stub := fake.ListObjectsStub
	fakeReturns := fake.listObjectsReturns
	fake.recordInvocation("ListObjects", []interface{}{arg1, arg2, arg3})
	fake.listObjectsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBucketStore) ListObjectsCallCount() int {
	fake.listObjectsMutex.RLock()
	defer fake.listObjectsMutex.RUnlock()
	return len(fake.listObjectsArgsForCall)
}

func (fake *FakeBucketStore) ListObjectsCalls(stub func(context.Context, *op.BucketRecord, op.ListObjectsParams) (op.ListObjectsResult, error)) {
	fake.listObjectsMutex.Lock()
	defer fake.listObjectsMutex.Unlock()
	fake.ListObjectsStub = stub
}

func (fake *FakeBucketStore) ListObjectsArgsForCall(i int) (context.Context, *op.BucketRecord, op.ListObjectsParams) {
	fake.listObjectsMutex.RLock()
	defer fake.listObjectsMutex.RUnlock()
	argsForCall := fake.listObjectsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBucketStore) ListObjectsReturns(result1 op.ListObjectsResult, result2 error) {
	fake.listObjectsMutex.Lock()
	defer fake.listObjectsMutex.Unlock()
	fake.ListObjectsStub = nil
	fake.listObjectsReturns = struct {
		result1 op.ListObjectsResult
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) ListObjectsReturnsOnCall(i int, result1 op.ListObjectsResult, result2 error) {
	fake.listObjectsMutex.Lock()
	defer fake.listObjectsMutex.Unlock()
	fake.ListObjectsStub = nil
	if fake.listObjectsReturnsOnCall == nil {
		fake.listObjectsReturnsOnCall = make(map[int]struct {
			result1 op.ListObjectsResult
			result2 error
		})
	}
	fake.listObjectsReturnsOnCall[i] = struct {
		result1 op.ListObjectsResult
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketStore) PutBucketAttrs(arg1 context.Context, arg2 *op.BucketRecord, arg3 map[string][]byte, arg4 []string) error {
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.putBucketAttrsMutex.Lock()
	ret, specificReturn := fake.putBucketAttrsReturnsOnCall[len(fake.putBucketAttrsArgsForCall)]
	fake.putBucketAttrsArgsForCall = append(fake.putBucketAttrsArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 map[string][]byte
		arg4 []string
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.PutBucketAttrsStub
	fakeReturns := fake.putBucketAttrsReturns
	fake.recordInvocation("PutBucketAttrs", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.putBucketAttrsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketStore) PutBucketAttrsCallCount() int {
	fake.putBucketAttrsMutex.RLock()
	defer fake.putBucketAttrsMutex.RUnlock()
	return len(fake.putBucketAttrsArgsForCall)
}

func (fake *FakeBucketStore) PutBucketAttrsCalls(stub func(context.Context, *op.BucketRecord, map[string][]byte, []string) error) {
	fake.putBucketAttrsMutex.Lock()
	defer fake.putBucketAttrsMutex.Unlock()
	fake.PutBucketAttrsStub = stub
}

func (fake *FakeBucketStore) PutBucketAttrsArgsForCall(i int) (context.Context, *op.BucketRecord, map[string][]byte, []string) {
	fake.putBucketAttrsMutex.RLock()
	defer fake.putBucketAttrsMutex.RUnlock()
	argsForCall := fake.putBucketAttrsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeBucketStore) PutBucketAttrsReturns(result1 error) {
	fake.putBucketAttrsMutex.Lock()
	defer fake.putBucketAttrsMutex.Unlock()
	fake.PutBucketAttrsStub = nil
	fake.putBucketAttrsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketStore) PutBucketAttrsReturnsOnCall(i int, result1 error) {
	fake.putBucketAttrsMutex.Lock()
	defer fake.putBucketAttrsMutex.Unlock()
	fake.PutBucketAttrsStub = nil
	if fake.putBucketAttrsReturnsOnCall == nil {
		fake.putBucketAttrsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putBucketAttrsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketStore) PutBucketInfo(arg1 context.Context, arg2 *op.BucketRecord) error {
	fake.putBucketInfoMutex.Lock()
	ret, specificReturn := fake.putBucketInfoReturnsOnCall[len(fake.putBucketInfoArgsForCall)]
	fake.putBucketInfoArgsForCall = append(fake.putBucketInfoArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}{arg1, arg2})
	stub := fake.PutBucketInfoStub
	fakeReturns := fake.putBucketInfoReturns
	fake.recordInvocation("PutBucketInfo", []interface{}{arg1, arg2})
	fake.putBucketInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBucketStore) PutBucketInfoCallCount() int {
	fake.putBucketInfoMutex.RLock()
	defer fake.putBucketInfoMutex.RUnlock()
	return len(fake.putBucketInfoArgsForCall)
}

func (fake *FakeBucketStore) PutBucketInfoCalls(stub func(context.Context, *op.BucketRecord) error) {
	fake.putBucketInfoMutex.Lock()
	defer fake.putBucketInfoMutex.Unlock()
	fake.PutBucketInfoStub = stub
}

func (fake *FakeBucketStore) PutBucketInfoArgsForCall(i int) (context.Context, *op.BucketRecord) {
	fake.putBucketInfoMutex.RLock()
	defer fake.putBucketInfoMutex.RUnlock()
	argsForCall := fake.putBucketInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBucketStore) PutBucketInfoReturns(result1 error) {
	fake.putBucketInfoMutex.Lock()
	defer fake.putBucketInfoMutex.Unlock()
	fake.PutBucketInfoStub = nil
	fake.putBucketInfoReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketStore) PutBucketInfoReturnsOnCall(i int, result1 error) {
	fake.putBucketInfoMutex.Lock()
	defer fake.putBucketInfoMutex.Unlock()
	fake.PutBucketInfoStub = nil
	if fake.putBucketInfoReturnsOnCall == nil {
		fake.putBucketInfoReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putBucketInfoReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBucketStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.BucketStore = new(FakeBucketStore)
