// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"io"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeObjectStore struct {
	CopyObjectStub        func(context.Context, *op.ObjectState, *op.BucketRecord, meta.ObjKey, op.CopyParams) (*op.PutResult, error)
	copyObjectMutex       sync.RWMutex
	copyObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.ObjectState
		arg3 *op.BucketRecord
		arg4 meta.ObjKey
		arg5 op.CopyParams
	}
	copyObjectReturns struct {
		result1 *op.PutResult
		result2 error
	}
	copyObjectReturnsOnCall map[int]struct {
		result1 *op.PutResult
		result2 error
	}
	DeleteObjectStub        func(context.Context, *op.BucketRecord, meta.ObjKey, op.DeleteParams) error
	deleteObjectMutex       sync.RWMutex
	deleteObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 op.DeleteParams
	}
	deleteObjectReturns struct {
		result1 error
	}
	deleteObjectReturnsOnCall map[int]struct {
		result1 error
	}
	PrefetchObjectStub        func(context.Context, *op.BucketRecord, meta.ObjKey) (*op.ObjectState, error)
	prefetchObjectMutex       sync.RWMutex
	prefetchObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
	}
	prefetchObjectReturns struct {
		result1 *op.ObjectState
		result2 error
	}
	prefetchObjectReturnsOnCall map[int]struct {
		result1 *op.ObjectState
		result2 error
	}
	PutObjectStub        func(context.Context, *op.BucketRecord, meta.ObjKey, io.Reader, op.PutParams) (*op.PutResult, error)
	putObjectMutex       sync.RWMutex
	putObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 io.Reader
		arg5 op.PutParams
	}
	putObjectReturns struct {
		result1 *op.PutResult
		result2 error
	}
	putObjectReturnsOnCall map[int]struct {
		result1 *op.PutResult
		result2 error
	}
	ReadObjectStub        func(context.Context, *op.ObjectState, op.ByteRange, io.Writer) error
	readObjectMutex       sync.RWMutex
	readObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.ObjectState
		arg3 op.ByteRange
		arg4 io.Writer
	}
	readObjectReturns struct {
		result1 error
	}
	readObjectReturnsOnCall map[int]struct {
		result1 error
	}
	SetObjectAttrsStub        func(context.Context, *op.ObjectState, map[string][]byte, []string) error
	setObjectAttrsMutex       sync.RWMutex
	setObjectAttrsArgsForCall []struct {
		arg1 context.Context
		arg2 *op.ObjectState
		arg3 map[string][]byte
		arg4 []string
	}
	setObjectAttrsReturns struct {
		result1 error
	}
	setObjectAttrsReturnsOnCall map[int]struct {
		result1 error
	}
	StatObjectStub        func(context.Context, *op.BucketRecord, meta.ObjKey) (*op.ObjectState, error)
	statObjectMutex       sync.RWMutex
	statObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
	}
	statObjectReturns struct {
		result1 *op.ObjectState
		result2 error
	}
	statObjectReturnsOnCall map[int]struct {
		result1 *op.ObjectState
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeObjectStore) CopyObject(arg1 context.Context, arg2 *op.ObjectState, arg3 *op.BucketRecord, arg4 meta.ObjKey, arg5 op.CopyParams) (*op.PutResult, error) {
	fake.copyObjectMutex.Lock()
	ret, specificReturn := fake.copyObjectReturnsOnCall[len(fake.copyObjectArgsForCall)]
	fake.copyObjectArgsForCall = append(fake.copyObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.ObjectState
		arg3 *op.BucketRecord
		arg4 meta.ObjKey
		arg5 op.CopyParams
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.CopyObjectStub
	fakeReturns := fake.copyObjectReturns
	fake.recordInvocation("CopyObject", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.copyObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeObjectStore) CopyObjectCallCount() int {
	fake.copyObjectMutex.RLock()
	defer fake.copyObjectMutex.RUnlock()
	return len(fake.copyObjectArgsForCall)
}

func (fake *FakeObjectStore) CopyObjectCalls(stub func(context.Context, *op.ObjectState, *op.BucketRecord, meta.ObjKey, op.CopyParams) (*op.PutResult, error)) {
	fake.copyObjectMutex.Lock()
	defer fake.copyObjectMutex.Unlock()
	fake.CopyObjectStub = stub
}

func (fake *FakeObjectStore) CopyObjectArgsForCall(i int) (context.Context, *op.ObjectState, *op.BucketRecord, meta.ObjKey, op.CopyParams) {
	fake.copyObjectMutex.RLock()
	defer fake.copyObjectMutex.RUnlock()
	argsForCall := fake.copyObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeObjectStore) CopyObjectReturns(result1 *op.PutResult, result2 error) {
	fake.copyObjectMutex.Lock()
	defer fake.copyObjectMutex.Unlock()
	fake.CopyObjectStub = nil
	fake.copyObjectReturns = struct {
		result1 *op.PutResult
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) CopyObjectReturnsOnCall(i int, result1 *op.PutResult, result2 error) {
	fake.copyObjectMutex.Lock()
	defer fake.copyObjectMutex.Unlock()
	fake.CopyObjectStub = nil
	if fake.copyObjectReturnsOnCall == nil {
		fake.copyObjectReturnsOnCall = make(map[int]struct {
			result1 *op.PutResult
			result2 error
		})
	}
	fake.copyObjectReturnsOnCall[i] = struct {
		result1 *op.PutResult
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) DeleteObject(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.ObjKey, arg4 op.DeleteParams) error {
	fake.deleteObjectMutex.Lock()
	ret, specificReturn := fake.deleteObjectReturnsOnCall[len(fake.deleteObjectArgsForCall)]
	fake.deleteObjectArgsForCall = append(fake.deleteObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 op.DeleteParams
	}{arg1, arg2, arg3, arg4})
	stub := fake.DeleteObjectStub
	fakeReturns := fake.deleteObjectReturns
	fake.recordInvocation("DeleteObject", []interface{}{arg1, arg2, arg3, arg4})
	fake.deleteObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeObjectStore) DeleteObjectCallCount() int {
	fake.deleteObjectMutex.RLock()
	defer fake.deleteObjectMutex.RUnlock()
	return len(fake.deleteObjectArgsForCall)
}

func (fake *FakeObjectStore) DeleteObjectCalls(stub func(context.Context, *op.BucketRecord, meta.ObjKey, op.DeleteParams) error) {
	fake.deleteObjectMutex.Lock()
	defer fake.deleteObjectMutex.Unlock()
	fake.DeleteObjectStub = stub
}

func (fake *FakeObjectStore) DeleteObjectArgsForCall(i int) (context.Context, *op.BucketRecord, meta.ObjKey, op.DeleteParams) {
	fake.deleteObjectMutex.RLock()
	defer fake.deleteObjectMutex.RUnlock()
	argsForCall := fake.deleteObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeObjectStore) DeleteObjectReturns(result1 error) {
	fake.deleteObjectMutex.Lock()
	defer fake.deleteObjectMutex.Unlock()
	fake.DeleteObjectStub = nil
	fake.deleteObjectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeObjectStore) DeleteObjectReturnsOnCall(i int, result1 error) {
	fake.deleteObjectMutex.Lock()
	defer fake.deleteObjectMutex.Unlock()
	fake.DeleteObjectStub = nil
	if fake.deleteObjectReturnsOnCall == nil {
		fake.deleteObjectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteObjectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeObjectStore) PrefetchObject(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.ObjKey) (*op.ObjectState, error) {
	fake.prefetchObjectMutex.Lock()
	ret, specificReturn := fake.prefetchObjectReturnsOnCall[len(fake.prefetchObjectArgsForCall)]
	fake.prefetchObjectArgsForCall = append(fake.prefetchObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
	}{arg1, arg2, arg3})
	stub := fake.PrefetchObjectStub
	fakeReturns := fake.prefetchObjectReturns
	fake.recordInvocation("PrefetchObject", []interface{}{arg1, arg2, arg3})
	fake.prefetchObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeObjectStore) PrefetchObjectCallCount() int {
	fake.prefetchObjectMutex.RLock()
	defer fake.prefetchObjectMutex.RUnlock()
	return len(fake.prefetchObjectArgsForCall)
}

func (fake *FakeObjectStore) PrefetchObjectCalls(stub func(context.Context, *op.BucketRecord, meta.ObjKey) (*op.ObjectState, error)) {
	fake.prefetchObjectMutex.Lock()
	defer fake.prefetchObjectMutex.Unlock()
	fake.PrefetchObjectStub = stub
}

func (fake *FakeObjectStore) PrefetchObjectArgsForCall(i int) (context.Context, *op.BucketRecord, meta.ObjKey) {
	fake.prefetchObjectMutex.RLock()
	defer fake.prefetchObjectMutex.RUnlock()
	argsForCall := fake.prefetchObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeObjectStore) PrefetchObjectReturns(result1 *op.ObjectState, result2 error) {
	fake.prefetchObjectMutex.Lock()
	defer fake.prefetchObjectMutex.Unlock()
	fake.PrefetchObjectStub = nil
	fake.prefetchObjectReturns = struct {
		result1 *op.ObjectState
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) PrefetchObjectReturnsOnCall(i int, result1 *op.ObjectState, result2 error) {
	fake.prefetchObjectMutex.Lock()
	defer fake.prefetchObjectMutex.Unlock()
	fake.PrefetchObjectStub = nil
	if fake.prefetchObjectReturnsOnCall == nil {
		fake.prefetchObjectReturnsOnCall = make(map[int]struct {
			result1 *op.ObjectState
			result2 error
		})
	}
	fake.prefetchObjectReturnsOnCall[i] = struct {
		result1 *op.ObjectState
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) PutObject(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.ObjKey, arg4 io.Reader, arg5 op.PutParams) (*op.PutResult, error) {
	fake.putObjectMutex.Lock()
	ret, specificReturn := fake.putObjectReturnsOnCall[len(fake.putObjectArgsForCall)]
	fake.putObjectArgsForCall = append(fake.putObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
		arg4 io.Reader
		arg5 op.PutParams
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PutObjectStub
	fakeReturns := fake.putObjectReturns
	fake.recordInvocation("PutObject", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.putObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeObjectStore) PutObjectCallCount() int {
	fake.putObjectMutex.RLock()
	defer fake.putObjectMutex.RUnlock()
	return len(fake.putObjectArgsForCall)
}

func (fake *FakeObjectStore) PutObjectCalls(stub func(context.Context, *op.BucketRecord, meta.ObjKey, io.Reader, op.PutParams) (*op.PutResult, error)) {
	fake.putObjectMutex.Lock()
	defer fake.putObjectMutex.Unlock()
	fake.PutObjectStub = stub
}

func (fake *FakeObjectStore) PutObjectArgsForCall(i int) (context.Context, *op.BucketRecord, meta.ObjKey, io.Reader, op.PutParams) {
	fake.putObjectMutex.RLock()
	defer fake.putObjectMutex.RUnlock()
	argsForCall := fake.putObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeObjectStore) PutObjectReturns(result1 *op.PutResult, result2 error) {
	fake.putObjectMutex.Lock()
	defer fake.putObjectMutex.Unlock()
	fake.PutObjectStub = nil
	fake.putObjectReturns = struct {
		result1 *op.PutResult
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) PutObjectReturnsOnCall(i int, result1 *op.PutResult, result2 error) {
	fake.putObjectMutex.Lock()
	defer fake.putObjectMutex.Unlock()
	fake.PutObjectStub = nil
	if fake.putObjectReturnsOnCall == nil {
		fake.putObjectReturnsOnCall = make(map[int]struct {
			result1 *op.PutResult
			result2 error
		})
	}
	fake.putObjectReturnsOnCall[i] = struct {
		result1 *op.PutResult
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) ReadObject(arg1 context.Context, arg2 *op.ObjectState, arg3 op.ByteRange, arg4 io.Writer) error {
	fake.readObjectMutex.Lock()
	ret, specificReturn := fake.readObjectReturnsOnCall[len(fake.readObjectArgsForCall)]
	fake.readObjectArgsForCall = append(fake.readObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.ObjectState
		arg3 op.ByteRange
		arg4 io.Writer
	}{arg1, arg2, arg3, arg4})
	stub := fake.ReadObjectStub
	fakeReturns := fake.readObjectReturns
	fake.recordInvocation("ReadObject", []interface{}{arg1, arg2, arg3, arg4})
	fake.readObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeObjectStore) ReadObjectCallCount() int {
	fake.readObjectMutex.RLock()
	defer fake.readObjectMutex.RUnlock()
	return len(fake.readObjectArgsForCall)
}

func (fake *FakeObjectStore) ReadObjectCalls(stub func(context.Context, *op.ObjectState, op.ByteRange, io.Writer) error) {
	fake.readObjectMutex.Lock()
	defer fake.readObjectMutex.Unlock()
	fake.ReadObjectStub = stub
}

func (fake *FakeObjectStore) ReadObjectArgsForCall(i int) (context.Context, *op.ObjectState, op.ByteRange, io.Writer) {
	fake.readObjectMutex.RLock()
	defer fake.readObjectMutex.RUnlock()
	argsForCall := fake.readObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeObjectStore) ReadObjectReturns(result1 error) {
	fake.readObjectMutex.Lock()
	defer fake.readObjectMutex.Unlock()
	fake.ReadObjectStub = nil
	fake.readObjectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeObjectStore) ReadObjectReturnsOnCall(i int, result1 error) {
	fake.readObjectMutex.Lock()
	defer fake.readObjectMutex.Unlock()
	fake.ReadObjectStub = nil
	if fake.readObjectReturnsOnCall == nil {
		fake.readObjectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.readObjectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeObjectStore) SetObjectAttrs(arg1 context.Context, arg2 *op.ObjectState, arg3 map[string][]byte, arg4 []string) error {
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.setObjectAttrsMutex.Lock()
	ret, specificReturn := fake.setObjectAttrsReturnsOnCall[len(fake.setObjectAttrsArgsForCall)]
	fake.setObjectAttrsArgsForCall = append(fake.setObjectAttrsArgsForCall, struct {
		arg1 context.Context
		arg2 *op.ObjectState
		arg3 map[string][]byte
		arg4 []string
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.SetObjectAttrsStub
	fakeReturns := fake.setObjectAttrsReturns
	fake.recordInvocation("SetObjectAttrs", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.setObjectAttrsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeObjectStore) SetObjectAttrsCallCount() int {
	fake.setObjectAttrsMutex.RLock()
	defer fake.setObjectAttrsMutex.RUnlock()
	return len(fake.setObjectAttrsArgsForCall)
}

func (fake *FakeObjectStore) SetObjectAttrsCalls(stub func(context.Context, *op.ObjectState, map[string][]byte, []string) error) {
	fake.setObjectAttrsMutex.Lock()
	defer fake.setObjectAttrsMutex.Unlock()
	fake.SetObjectAttrsStub = stub
}

func (fake *FakeObjectStore) SetObjectAttrsArgsForCall(i int) (context.Context, *op.ObjectState, map[string][]byte, []string) {
	fake.setObjectAttrsMutex.RLock()
	defer fake.setObjectAttrsMutex.RUnlock()
	argsForCall := fake.setObjectAttrsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeObjectStore) SetObjectAttrsReturns(result1 error) {
	fake.setObjectAttrsMutex.Lock()
	defer fake.setObjectAttrsMutex.Unlock()
	fake.SetObjectAttrsStub = nil
	fake.setObjectAttrsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeObjectStore) SetObjectAttrsReturnsOnCall(i int, result1 error) {
	fake.setObjectAttrsMutex.Lock()
	defer fake.setObjectAttrsMutex.Unlock()
	fake.SetObjectAttrsStub = nil
	if fake.setObjectAttrsReturnsOnCall == nil {
		fake.setObjectAttrsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setObjectAttrsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeObjectStore) StatObject(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.ObjKey) (*op.ObjectState, error) {
	fake.statObjectMutex.Lock()
	ret, specificReturn := fake.statObjectReturnsOnCall[len(fake.statObjectArgsForCall)]
	fake.statObjectArgsForCall = append(fake.statObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.ObjKey
	}{arg1, arg2, arg3})
	stub := fake.StatObjectStub
	fakeReturns := fake.statObjectReturns
	fake.recordInvocation("StatObject", []interface{}{arg1, arg2, arg3})
	fake.statObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeObjectStore) StatObjectCallCount() int {
	fake.statObjectMutex.RLock()
	defer fake.statObjectMutex.RUnlock()
	return len(fake.statObjectArgsForCall)
}

func (fake *FakeObjectStore) StatObjectCalls(stub func(context.Context, *op.BucketRecord, meta.ObjKey) (*op.ObjectState, error)) {
	fake.statObjectMutex.Lock()
	defer fake.statObjectMutex.Unlock()
	fake.StatObjectStub = stub
}

func (fake *FakeObjectStore) StatObjectArgsForCall(i int) (context.Context, *op.BucketRecord, meta.ObjKey) {
	fake.statObjectMutex.RLock()
	defer fake.statObjectMutex.RUnlock()
	argsForCall := fake.statObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeObjectStore) StatObjectReturns(result1 *op.ObjectState, result2 error) {
	fake.statObjectMutex.Lock()
	defer fake.statObjectMutex.Unlock()
	fake.StatObjectStub = nil
	fake.statObjectReturns = struct {
		result1 *op.ObjectState
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) StatObjectReturnsOnCall(i int, result1 *op.ObjectState, result2 error) {
	fake.statObjectMutex.Lock()
	defer fake.statObjectMutex.Unlock()
	fake.StatObjectStub = nil
	if fake.statObjectReturnsOnCall == nil {
		fake.statObjectReturnsOnCall = make(map[int]struct {
			result1 *op.ObjectState
			result2 error
		})
	}
	fake.statObjectReturnsOnCall[i] = struct {
		result1 *op.ObjectState
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeObjectStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.ObjectStore = new(FakeObjectStore)
