// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"sync"

	"github.com/jhoblitt/rgw-go/internal/denc"
	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeZoneInfo struct {
	PeriodStub        func() meta.Period
	periodMutex       sync.RWMutex
	periodArgsForCall []struct {
	}
	periodReturns struct {
		result1 meta.Period
	}
	periodReturnsOnCall map[int]struct {
		result1 meta.Period
	}
	PlacementStub        func(meta.PlacementRule) (op.Placement, error)
	placementMutex       sync.RWMutex
	placementArgsForCall []struct {
		arg1 meta.PlacementRule
	}
	placementReturns struct {
		result1 op.Placement
		result2 error
	}
	placementReturnsOnCall map[int]struct {
		result1 op.Placement
		result2 error
	}
	RealmStub        func() meta.Realm
	realmMutex       sync.RWMutex
	realmArgsForCall []struct {
	}
	realmReturns struct {
		result1 meta.Realm
	}
	realmReturnsOnCall map[int]struct {
		result1 meta.Realm
	}
	ReleaseStub        func() denc.Release
	releaseMutex       sync.RWMutex
	releaseArgsForCall []struct {
	}
	releaseReturns struct {
		result1 denc.Release
	}
	releaseReturnsOnCall map[int]struct {
		result1 denc.Release
	}
	ZoneStub        func() meta.Zone
	zoneMutex       sync.RWMutex
	zoneArgsForCall []struct {
	}
	zoneReturns struct {
		result1 meta.Zone
	}
	zoneReturnsOnCall map[int]struct {
		result1 meta.Zone
	}
	ZoneGroupStub        func() meta.ZoneGroup
	zoneGroupMutex       sync.RWMutex
	zoneGroupArgsForCall []struct {
	}
	zoneGroupReturns struct {
		result1 meta.ZoneGroup
	}
	zoneGroupReturnsOnCall map[int]struct {
		result1 meta.ZoneGroup
	}
	ZoneParamsStub        func() meta.ZoneParams
	zoneParamsMutex       sync.RWMutex
	zoneParamsArgsForCall []struct {
	}
	zoneParamsReturns struct {
		result1 meta.ZoneParams
	}
	zoneParamsReturnsOnCall map[int]struct {
		result1 meta.ZoneParams
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeZoneInfo) Period() meta.Period {
	fake.periodMutex.Lock()
	ret, specificReturn := fake.periodReturnsOnCall[len(fake.periodArgsForCall)]
	fake.periodArgsForCall = append(fake.periodArgsForCall, struct {
	}{})
	stub := fake.PeriodStub
	fakeReturns := fake.periodReturns
	fake.recordInvocation("Period", []interface{}{})
	fake.periodMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeZoneInfo) PeriodCallCount() int {
	fake.periodMutex.RLock()
	defer fake.periodMutex.RUnlock()
	return len(fake.periodArgsForCall)
}

func (fake *FakeZoneInfo) PeriodCalls(stub func() meta.Period) {
	fake.periodMutex.Lock()
	defer fake.periodMutex.Unlock()
	fake.PeriodStub = stub
}

func (fake *FakeZoneInfo) PeriodReturns(result1 meta.Period) {
	fake.periodMutex.Lock()
	defer fake.periodMutex.Unlock()
	fake.PeriodStub = nil
	fake.periodReturns = struct {
		result1 meta.Period
	}{result1}
}

func (fake *FakeZoneInfo) PeriodReturnsOnCall(i int, result1 meta.Period) {
	fake.periodMutex.Lock()
	defer fake.periodMutex.Unlock()
	fake.PeriodStub = nil
	if fake.periodReturnsOnCall == nil {
		fake.periodReturnsOnCall = make(map[int]struct {
			result1 meta.Period
		})
	}
	fake.periodReturnsOnCall[i] = struct {
		result1 meta.Period
	}{result1}
}

func (fake *FakeZoneInfo) Placement(arg1 meta.PlacementRule) (op.Placement, error) {
	fake.placementMutex.Lock()
	ret, specificReturn := fake.placementReturnsOnCall[len(fake.placementArgsForCall)]
	fake.placementArgsForCall = append(fake.placementArgsForCall, struct {
		arg1 meta.PlacementRule
	}{arg1})
	stub := fake.PlacementStub
	fakeReturns := fake.placementReturns
	fake.recordInvocation("Placement", []interface{}{arg1})
	fake.placementMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeZoneInfo) PlacementCallCount() int {
	fake.placementMutex.RLock()
	defer fake.placementMutex.RUnlock()
	return len(fake.placementArgsForCall)
}

func (fake *FakeZoneInfo) PlacementCalls(stub func(meta.PlacementRule) (op.Placement, error)) {
	fake.placementMutex.Lock()
	defer fake.placementMutex.Unlock()
	fake.PlacementStub = stub
}

func (fake *FakeZoneInfo) PlacementArgsForCall(i int) meta.PlacementRule {
	fake.placementMutex.RLock()
	defer fake.placementMutex.RUnlock()
	argsForCall := fake.placementArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeZoneInfo) PlacementReturns(result1 op.Placement, result2 error) {
	fake.placementMutex.Lock()
	defer fake.placementMutex.Unlock()
	fake.PlacementStub = nil
	fake.placementReturns = struct {
		result1 op.Placement
		result2 error
	}{result1, result2}
}

func (fake *FakeZoneInfo) PlacementReturnsOnCall(i int, result1 op.Placement, result2 error) {
	fake.placementMutex.Lock()
	defer fake.placementMutex.Unlock()
	fake.PlacementStub = nil
	if fake.placementReturnsOnCall == nil {
		fake.placementReturnsOnCall = make(map[int]struct {
			result1 op.Placement
			result2 error
		})
	}
	fake.placementReturnsOnCall[i] = struct {
		result1 op.Placement
		result2 error
	}{result1, result2}
}

func (fake *FakeZoneInfo) Realm() meta.Realm {
	fake.realmMutex.Lock()
	ret, specificReturn := fake.realmReturnsOnCall[len(fake.realmArgsForCall)]
	fake.realmArgsForCall = append(fake.realmArgsForCall, struct {
	}{})
	stub := fake.RealmStub
	fakeReturns := fake.realmReturns
	fake.recordInvocation("Realm", []interface{}{})
	fake.realmMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeZoneInfo) RealmCallCount() int {
	fake.realmMutex.RLock()
	defer fake.realmMutex.RUnlock()
	return len(fake.realmArgsForCall)
}

func (fake *FakeZoneInfo) RealmCalls(stub func() meta.Realm) {
	fake.realmMutex.Lock()
	defer fake.realmMutex.Unlock()
	fake.RealmStub = stub
}

func (fake *FakeZoneInfo) RealmReturns(result1 meta.Realm) {
	fake.realmMutex.Lock()
	defer fake.realmMutex.Unlock()
	fake.RealmStub = nil
	fake.realmReturns = struct {
		result1 meta.Realm
	}{result1}
}

func (fake *FakeZoneInfo) RealmReturnsOnCall(i int, result1 meta.Realm) {
	fake.realmMutex.Lock()
	defer fake.realmMutex.Unlock()
	fake.RealmStub = nil
	if fake.realmReturnsOnCall == nil {
		fake.realmReturnsOnCall = make(map[int]struct {
			result1 meta.Realm
		})
	}
	fake.realmReturnsOnCall[i] = struct {
		result1 meta.Realm
	}{result1}
}

func (fake *FakeZoneInfo) Release() denc.Release {
	fake.releaseMutex.Lock()
	ret, specificReturn := fake.releaseReturnsOnCall[len(fake.releaseArgsForCall)]
	fake.releaseArgsForCall = append(fake.releaseArgsForCall, struct {
	}{})
	stub := fake.ReleaseStub
	fakeReturns := fake.releaseReturns
	fake.recordInvocation("Release", []interface{}{})
	fake.releaseMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeZoneInfo) ReleaseCallCount() int {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	return len(fake.releaseArgsForCall)
}

func (fake *FakeZoneInfo) ReleaseCalls(stub func() denc.Release) {
	fake.releaseMutex.Lock()
	defer fake.releaseMutex.Unlock()
	fake.ReleaseStub = stub
}

func (fake *FakeZoneInfo) ReleaseReturns(result1 denc.Release) {
	fake.releaseMutex.Lock()
	defer fake.releaseMutex.Unlock()
	fake.ReleaseStub = nil
	fake.releaseReturns = struct {
		result1 denc.Release
	}{result1}
}

func (fake *FakeZoneInfo) ReleaseReturnsOnCall(i int, result1 denc.Release) {
	fake.releaseMutex.Lock()
	defer fake.releaseMutex.Unlock()
	fake.ReleaseStub = nil
	if fake.releaseReturnsOnCall == nil {
		fake.releaseReturnsOnCall = make(map[int]struct {
			result1 denc.Release
		})
	}
	fake.releaseReturnsOnCall[i] = struct {
		result1 denc.Release
	}{result1}
}

func (fake *FakeZoneInfo) Zone() meta.Zone {
	fake.zoneMutex.Lock()
	ret, specificReturn := fake.zoneReturnsOnCall[len(fake.zoneArgsForCall)]
	fake.zoneArgsForCall = append(fake.zoneArgsForCall, struct {
	}{})
	stub := fake.ZoneStub
	fakeReturns := fake.zoneReturns
	fake.recordInvocation("Zone", []interface{}{})
	fake.zoneMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeZoneInfo) ZoneCallCount() int {
	fake.zoneMutex.RLock()
	defer fake.zoneMutex.RUnlock()
	return len(fake.zoneArgsForCall)
}

func (fake *FakeZoneInfo) ZoneCalls(stub func() meta.Zone) {
	fake.zoneMutex.Lock()
	defer fake.zoneMutex.Unlock()
	fake.ZoneStub = stub
}

func (fake *FakeZoneInfo) ZoneReturns(result1 meta.Zone) {
	fake.zoneMutex.Lock()
	defer fake.zoneMutex.Unlock()
	fake.ZoneStub = nil
	fake.zoneReturns = struct {
		result1 meta.Zone
	}{result1}
}

func (fake *FakeZoneInfo) ZoneReturnsOnCall(i int, result1 meta.Zone) {
	fake.zoneMutex.Lock()
	defer fake.zoneMutex.Unlock()
	fake.ZoneStub = nil
	if fake.zoneReturnsOnCall == nil {
		fake.zoneReturnsOnCall = make(map[int]struct {
			result1 meta.Zone
		})
	}
	fake.zoneReturnsOnCall[i] = struct {
		result1 meta.Zone
	}{result1}
}

func (fake *FakeZoneInfo) ZoneGroup() meta.ZoneGroup {
	fake.zoneGroupMutex.Lock()
	ret, specificReturn := fake.zoneGroupReturnsOnCall[len(fake.zoneGroupArgsForCall)]
	fake.zoneGroupArgsForCall = append(fake.zoneGroupArgsForCall, struct {
	}{})
	stub := fake.ZoneGroupStub
	fakeReturns := fake.zoneGroupReturns
	fake.recordInvocation("ZoneGroup", []interface{}{})
	fake.zoneGroupMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeZoneInfo) ZoneGroupCallCount() int {
	fake.zoneGroupMutex.RLock()
	defer fake.zoneGroupMutex.RUnlock()
	return len(fake.zoneGroupArgsForCall)
}

func (fake *FakeZoneInfo) ZoneGroupCalls(stub func() meta.ZoneGroup) {
	fake.zoneGroupMutex.Lock()
	defer fake.zoneGroupMutex.Unlock()
	fake.ZoneGroupStub = stub
}

func (fake *FakeZoneInfo) ZoneGroupReturns(result1 meta.ZoneGroup) {
	fake.zoneGroupMutex.Lock()
	defer fake.zoneGroupMutex.Unlock()
	fake.ZoneGroupStub = nil
	fake.zoneGroupReturns = struct {
		result1 meta.ZoneGroup
	}{result1}
}

func (fake *FakeZoneInfo) ZoneGroupReturnsOnCall(i int, result1 meta.ZoneGroup) {
	fake.zoneGroupMutex.Lock()
	defer fake.zoneGroupMutex.Unlock()
	fake.ZoneGroupStub = nil
	if fake.zoneGroupReturnsOnCall == nil {
		fake.zoneGroupReturnsOnCall = make(map[int]struct {
			result1 meta.ZoneGroup
		})
	}
	fake.zoneGroupReturnsOnCall[i] = struct {
		result1 meta.ZoneGroup
	}{result1}
}

func (fake *FakeZoneInfo) ZoneParams() meta.ZoneParams {
	fake.zoneParamsMutex.Lock()
	ret, specificReturn := fake.zoneParamsReturnsOnCall[len(fake.zoneParamsArgsForCall)]
	fake.zoneParamsArgsForCall = append(fake.zoneParamsArgsForCall, struct {
	}{})
	stub := fake.ZoneParamsStub
	fakeReturns := fake.zoneParamsReturns
	fake.recordInvocation("ZoneParams", []interface{}{})
	fake.zoneParamsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeZoneInfo) ZoneParamsCallCount() int {
	fake.zoneParamsMutex.RLock()
	defer fake.zoneParamsMutex.RUnlock()
	return len(fake.zoneParamsArgsForCall)
}

func (fake *FakeZoneInfo) ZoneParamsCalls(stub func() meta.ZoneParams) {
	fake.zoneParamsMutex.Lock()
	defer fake.zoneParamsMutex.Unlock()
	fake.ZoneParamsStub = stub
}

func (fake *FakeZoneInfo) ZoneParamsReturns(result1 meta.ZoneParams) {
	fake.zoneParamsMutex.Lock()
	defer fake.zoneParamsMutex.Unlock()
	fake.ZoneParamsStub = nil
	fake.zoneParamsReturns = struct {
		result1 meta.ZoneParams
	}{result1}
}

func (fake *FakeZoneInfo) ZoneParamsReturnsOnCall(i int, result1 meta.ZoneParams) {
	fake.zoneParamsMutex.Lock()
	defer fake.zoneParamsMutex.Unlock()
	fake.ZoneParamsStub = nil
	if fake.zoneParamsReturnsOnCall == nil {
		fake.zoneParamsReturnsOnCall = make(map[int]struct {
			result1 meta.ZoneParams
		})
	}
	fake.zoneParamsReturnsOnCall[i] = struct {
		result1 meta.ZoneParams
	}{result1}
}

func (fake *FakeZoneInfo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeZoneInfo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.ZoneInfo = new(FakeZoneInfo)
