// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/acl"
	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
	"github.com/jhoblitt/rgw-go/internal/policy"
)

type FakeAuthorizer struct {
	VerifyBucketStub        func(context.Context, *op.Request, policy.Action, acl.Permission) error
	verifyBucketMutex       sync.RWMutex
	verifyBucketArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
	}
	verifyBucketReturns struct {
		result1 error
	}
	verifyBucketReturnsOnCall map[int]struct {
		result1 error
	}
	VerifyBucketInStub        func(context.Context, *op.Request, policy.Action, acl.Permission, *op.BucketRecord, meta.ObjKey) error
	verifyBucketInMutex       sync.RWMutex
	verifyBucketInArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
		arg5 *op.BucketRecord
		arg6 meta.ObjKey
	}
	verifyBucketInReturns struct {
		result1 error
	}
	verifyBucketInReturnsOnCall map[int]struct {
		result1 error
	}
	VerifyObjectStub        func(context.Context, *op.Request, policy.Action, acl.Permission) error
	verifyObjectMutex       sync.RWMutex
	verifyObjectArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
	}
	verifyObjectReturns struct {
		result1 error
	}
	verifyObjectReturnsOnCall map[int]struct {
		result1 error
	}
	VerifyObjectInStub        func(context.Context, *op.Request, policy.Action, acl.Permission, *op.BucketRecord, *op.ObjectState) error
	verifyObjectInMutex       sync.RWMutex
	verifyObjectInArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
		arg5 *op.BucketRecord
		arg6 *op.ObjectState
	}
	verifyObjectInReturns struct {
		result1 error
	}
	verifyObjectInReturnsOnCall map[int]struct {
		result1 error
	}
	VerifyUserStub        func(context.Context, *op.Request, policy.Action) error
	verifyUserMutex       sync.RWMutex
	verifyUserArgsForCall []struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
	}
	verifyUserReturns struct {
		result1 error
	}
	verifyUserReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthorizer) VerifyBucket(arg1 context.Context, arg2 *op.Request, arg3 policy.Action, arg4 acl.Permission) error {
	fake.verifyBucketMutex.Lock()
	ret, specificReturn := fake.verifyBucketReturnsOnCall[len(fake.verifyBucketArgsForCall)]
	fake.verifyBucketArgsForCall = append(fake.verifyBucketArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
	}{arg1, arg2, arg3, arg4})
	stub := fake.VerifyBucketStub
	fakeReturns := fake.verifyBucketReturns
	fake.recordInvocation("VerifyBucket", []interface{}{arg1, arg2, arg3, arg4})
	fake.verifyBucketMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthorizer) VerifyBucketCallCount() int {
	fake.verifyBucketMutex.RLock()
	defer fake.verifyBucketMutex.RUnlock()
	return len(fake.verifyBucketArgsForCall)
}

func (fake *FakeAuthorizer) VerifyBucketCalls(stub func(context.Context, *op.Request, policy.Action, acl.Permission) error) {
	fake.verifyBucketMutex.Lock()
	defer fake.verifyBucketMutex.Unlock()
	fake.VerifyBucketStub = stub
}

func (fake *FakeAuthorizer) VerifyBucketArgsForCall(i int) (context.Context, *op.Request, policy.Action, acl.Permission) {
	fake.verifyBucketMutex.RLock()
	defer fake.verifyBucketMutex.RUnlock()
	argsForCall := fake.verifyBucketArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAuthorizer) VerifyBucketReturns(result1 error) {
	fake.verifyBucketMutex.Lock()
	defer fake.verifyBucketMutex.Unlock()
	fake.VerifyBucketStub = nil
	fake.verifyBucketReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyBucketReturnsOnCall(i int, result1 error) {
	fake.verifyBucketMutex.Lock()
	defer fake.verifyBucketMutex.Unlock()
	fake.VerifyBucketStub = nil
	if fake.verifyBucketReturnsOnCall == nil {
		fake.verifyBucketReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyBucketReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyBucketIn(arg1 context.Context, arg2 *op.Request, arg3 policy.Action, arg4 acl.Permission, arg5 *op.BucketRecord, arg6 meta.ObjKey) error {
	fake.verifyBucketInMutex.Lock()
	ret, specificReturn := fake.verifyBucketInReturnsOnCall[len(fake.verifyBucketInArgsForCall)]
	fake.verifyBucketInArgsForCall = append(fake.verifyBucketInArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
		arg5 *op.BucketRecord
		arg6 meta.ObjKey
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.VerifyBucketInStub
	fakeReturns := fake.verifyBucketInReturns
	fake.recordInvocation("VerifyBucketIn", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.verifyBucketInMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthorizer) VerifyBucketInCallCount() int {
	fake.verifyBucketInMutex.RLock()
	defer fake.verifyBucketInMutex.RUnlock()
	return len(fake.verifyBucketInArgsForCall)
}

func (fake *FakeAuthorizer) VerifyBucketInCalls(stub func(context.Context, *op.Request, policy.Action, acl.Permission, *op.BucketRecord, meta.ObjKey) error) {
	fake.verifyBucketInMutex.Lock()
	defer fake.verifyBucketInMutex.Unlock()
	fake.VerifyBucketInStub = stub
}

func (fake *FakeAuthorizer) VerifyBucketInArgsForCall(i int) (context.Context, *op.Request, policy.Action, acl.Permission, *op.BucketRecord, meta.ObjKey) {
	fake.verifyBucketInMutex.RLock()
	defer fake.verifyBucketInMutex.RUnlock()
	argsForCall := fake.verifyBucketInArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeAuthorizer) VerifyBucketInReturns(result1 error) {
	fake.verifyBucketInMutex.Lock()
	defer fake.verifyBucketInMutex.Unlock()
	fake.VerifyBucketInStub = nil
	fake.verifyBucketInReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyBucketInReturnsOnCall(i int, result1 error) {
	fake.verifyBucketInMutex.Lock()
	defer fake.verifyBucketInMutex.Unlock()
	fake.VerifyBucketInStub = nil
	if fake.verifyBucketInReturnsOnCall == nil {
		fake.verifyBucketInReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyBucketInReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyObject(arg1 context.Context, arg2 *op.Request, arg3 policy.Action, arg4 acl.Permission) error {
	fake.verifyObjectMutex.Lock()
	ret, specificReturn := fake.verifyObjectReturnsOnCall[len(fake.verifyObjectArgsForCall)]
	fake.verifyObjectArgsForCall = append(fake.verifyObjectArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
	}{arg1, arg2, arg3, arg4})
	stub := fake.VerifyObjectStub
	fakeReturns := fake.verifyObjectReturns
	fake.recordInvocation("VerifyObject", []interface{}{arg1, arg2, arg3, arg4})
	fake.verifyObjectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthorizer) VerifyObjectCallCount() int {
	fake.verifyObjectMutex.RLock()
	defer fake.verifyObjectMutex.RUnlock()
	return len(fake.verifyObjectArgsForCall)
}

func (fake *FakeAuthorizer) VerifyObjectCalls(stub func(context.Context, *op.Request, policy.Action, acl.Permission) error) {
	fake.verifyObjectMutex.Lock()
	defer fake.verifyObjectMutex.Unlock()
	fake.VerifyObjectStub = stub
}

func (fake *FakeAuthorizer) VerifyObjectArgsForCall(i int) (context.Context, *op.Request, policy.Action, acl.Permission) {
	fake.verifyObjectMutex.RLock()
	defer fake.verifyObjectMutex.RUnlock()
	argsForCall := fake.verifyObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAuthorizer) VerifyObjectReturns(result1 error) {
	fake.verifyObjectMutex.Lock()
	defer fake.verifyObjectMutex.Unlock()
	fake.VerifyObjectStub = nil
	fake.verifyObjectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyObjectReturnsOnCall(i int, result1 error) {
	fake.verifyObjectMutex.Lock()
	defer fake.verifyObjectMutex.Unlock()
	fake.VerifyObjectStub = nil
	if fake.verifyObjectReturnsOnCall == nil {
		fake.verifyObjectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyObjectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyObjectIn(arg1 context.Context, arg2 *op.Request, arg3 policy.Action, arg4 acl.Permission, arg5 *op.BucketRecord, arg6 *op.ObjectState) error {
	fake.verifyObjectInMutex.Lock()
	ret, specificReturn := fake.verifyObjectInReturnsOnCall[len(fake.verifyObjectInArgsForCall)]
	fake.verifyObjectInArgsForCall = append(fake.verifyObjectInArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
		arg4 acl.Permission
		arg5 *op.BucketRecord
		arg6 *op.ObjectState
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.VerifyObjectInStub
	fakeReturns := fake.verifyObjectInReturns
	fake.recordInvocation("VerifyObjectIn", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.verifyObjectInMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthorizer) VerifyObjectInCallCount() int {
	fake.verifyObjectInMutex.RLock()
	defer fake.verifyObjectInMutex.RUnlock()
	return len(fake.verifyObjectInArgsForCall)
}

func (fake *FakeAuthorizer) VerifyObjectInCalls(stub func(context.Context, *op.Request, policy.Action, acl.Permission, *op.BucketRecord, *op.ObjectState) error) {
	fake.verifyObjectInMutex.Lock()
	defer fake.verifyObjectInMutex.Unlock()
	fake.VerifyObjectInStub = stub
}

func (fake *FakeAuthorizer) VerifyObjectInArgsForCall(i int) (context.Context, *op.Request, policy.Action, acl.Permission, *op.BucketRecord, *op.ObjectState) {
	fake.verifyObjectInMutex.RLock()
	defer fake.verifyObjectInMutex.RUnlock()
	argsForCall := fake.verifyObjectInArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeAuthorizer) VerifyObjectInReturns(result1 error) {
	fake.verifyObjectInMutex.Lock()
	defer fake.verifyObjectInMutex.Unlock()
	fake.VerifyObjectInStub = nil
	fake.verifyObjectInReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyObjectInReturnsOnCall(i int, result1 error) {
	fake.verifyObjectInMutex.Lock()
	defer fake.verifyObjectInMutex.Unlock()
	fake.VerifyObjectInStub = nil
	if fake.verifyObjectInReturnsOnCall == nil {
		fake.verifyObjectInReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyObjectInReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyUser(arg1 context.Context, arg2 *op.Request, arg3 policy.Action) error {
	fake.verifyUserMutex.Lock()
	ret, specificReturn := fake.verifyUserReturnsOnCall[len(fake.verifyUserArgsForCall)]
	fake.verifyUserArgsForCall = append(fake.verifyUserArgsForCall, struct {
		arg1 context.Context
		arg2 *op.Request
		arg3 policy.Action
	}{arg1, arg2, arg3})
	stub := fake.VerifyUserStub
	fakeReturns := fake.verifyUserReturns
	fake.recordInvocation("VerifyUser", []interface{}{arg1, arg2, arg3})
	fake.verifyUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthorizer) VerifyUserCallCount() int {
	fake.verifyUserMutex.RLock()
	defer fake.verifyUserMutex.RUnlock()
	return len(fake.verifyUserArgsForCall)
}

func (fake *FakeAuthorizer) VerifyUserCalls(stub func(context.Context, *op.Request, policy.Action) error) {
	fake.verifyUserMutex.Lock()
	defer fake.verifyUserMutex.Unlock()
	fake.VerifyUserStub = stub
}

func (fake *FakeAuthorizer) VerifyUserArgsForCall(i int) (context.Context, *op.Request, policy.Action) {
	fake.verifyUserMutex.RLock()
	defer fake.verifyUserMutex.RUnlock()
	argsForCall := fake.verifyUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAuthorizer) VerifyUserReturns(result1 error) {
	fake.verifyUserMutex.Lock()
	defer fake.verifyUserMutex.Unlock()
	fake.VerifyUserStub = nil
	fake.verifyUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) VerifyUserReturnsOnCall(i int, result1 error) {
	fake.verifyUserMutex.Lock()
	defer fake.verifyUserMutex.Unlock()
	fake.VerifyUserStub = nil
	if fake.verifyUserReturnsOnCall == nil {
		fake.verifyUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthorizer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthorizer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.Authorizer = new(FakeAuthorizer)
