// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeUsageReader struct {
	ReadUsageStub        func(context.Context, string, string, uint64, uint64, uint32, *op.UsageIter) ([]op.UsageRecord, bool, error)
	readUsageMutex       sync.RWMutex
	readUsageArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 uint64
		arg5 uint64
		arg6 uint32
		arg7 *op.UsageIter
	}
	readUsageReturns struct {
		result1 []op.UsageRecord
		result2 bool
		result3 error
	}
	readUsageReturnsOnCall map[int]struct {
		result1 []op.UsageRecord
		result2 bool
		result3 error
	}
	TrimUsageStub        func(context.Context, string, string, uint64, uint64) error
	trimUsageMutex       sync.RWMutex
	trimUsageArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 uint64
		arg5 uint64
	}
	trimUsageReturns struct {
		result1 error
	}
	trimUsageReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUsageReader) ReadUsage(arg1 context.Context, arg2 string, arg3 string, arg4 uint64, arg5 uint64, arg6 uint32, arg7 *op.UsageIter) ([]op.UsageRecord, bool, error) {
	fake.readUsageMutex.Lock()
	ret, specificReturn := fake.readUsageReturnsOnCall[len(fake.readUsageArgsForCall)]
	fake.readUsageArgsForCall = append(fake.readUsageArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 uint64
		arg5 uint64
		arg6 uint32
		arg7 *op.UsageIter
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	stub := fake.ReadUsageStub
	fakeReturns := fake.readUsageReturns
	fake.recordInvocation("ReadUsage", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.readUsageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeUsageReader) ReadUsageCallCount() int {
	fake.readUsageMutex.RLock()
	defer fake.readUsageMutex.RUnlock()
	return len(fake.readUsageArgsForCall)
}

func (fake *FakeUsageReader) ReadUsageCalls(stub func(context.Context, string, string, uint64, uint64, uint32, *op.UsageIter) ([]op.UsageRecord, bool, error)) {
	fake.readUsageMutex.Lock()
	defer fake.readUsageMutex.Unlock()
	fake.ReadUsageStub = stub
}

func (fake *FakeUsageReader) ReadUsageArgsForCall(i int) (context.Context, string, string, uint64, uint64, uint32, *op.UsageIter) {
	fake.readUsageMutex.RLock()
	defer fake.readUsageMutex.RUnlock()
	argsForCall := fake.readUsageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7
}

func (fake *FakeUsageReader) ReadUsageReturns(result1 []op.UsageRecord, result2 bool, result3 error) {
	fake.readUsageMutex.Lock()
	defer fake.readUsageMutex.Unlock()
	fake.ReadUsageStub = nil
	fake.readUsageReturns = struct {
		result1 []op.UsageRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeUsageReader) ReadUsageReturnsOnCall(i int, result1 []op.UsageRecord, result2 bool, result3 error) {
	fake.readUsageMutex.Lock()
	defer fake.readUsageMutex.Unlock()
	fake.ReadUsageStub = nil
	if fake.readUsageReturnsOnCall == nil {
		fake.readUsageReturnsOnCall = make(map[int]struct {
			result1 []op.UsageRecord
			result2 bool
			result3 error
		})
	}
	fake.readUsageReturnsOnCall[i] = struct {
		result1 []op.UsageRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeUsageReader) TrimUsage(arg1 context.Context, arg2 string, arg3 string, arg4 uint64, arg5 uint64) error {
	fake.trimUsageMutex.Lock()
	ret, specificReturn := fake.trimUsageReturnsOnCall[len(fake.trimUsageArgsForCall)]
	fake.trimUsageArgsForCall = append(fake.trimUsageArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 uint64
		arg5 uint64
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.TrimUsageStub
	fakeReturns := fake.trimUsageReturns
	fake.recordInvocation("TrimUsage", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.trimUsageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeUsageReader) TrimUsageCallCount() int {
	fake.trimUsageMutex.RLock()
	defer fake.trimUsageMutex.RUnlock()
	return len(fake.trimUsageArgsForCall)
}

func (fake *FakeUsageReader) TrimUsageCalls(stub func(context.Context, string, string, uint64, uint64) error) {
	fake.trimUsageMutex.Lock()
	defer fake.trimUsageMutex.Unlock()
	fake.TrimUsageStub = stub
}

func (fake *FakeUsageReader) TrimUsageArgsForCall(i int) (context.Context, string, string, uint64, uint64) {
	fake.trimUsageMutex.RLock()
	defer fake.trimUsageMutex.RUnlock()
	argsForCall := fake.trimUsageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeUsageReader) TrimUsageReturns(result1 error) {
	fake.trimUsageMutex.Lock()
	defer fake.trimUsageMutex.Unlock()
	fake.TrimUsageStub = nil
	fake.trimUsageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUsageReader) TrimUsageReturnsOnCall(i int, result1 error) {
	fake.trimUsageMutex.Lock()
	defer fake.trimUsageMutex.Unlock()
	fake.TrimUsageStub = nil
	if fake.trimUsageReturnsOnCall == nil {
		fake.trimUsageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.trimUsageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUsageReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUsageReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.UsageReader = new(FakeUsageReader)
