// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeAccountStore struct {
	AccountNameStub        func(context.Context, string) (string, error)
	accountNameMutex       sync.RWMutex
	accountNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	accountNameReturns struct {
		result1 string
		result2 error
	}
	accountNameReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetAccountStub        func(context.Context, string) (*op.AccountRecord, error)
	getAccountMutex       sync.RWMutex
	getAccountArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getAccountReturns struct {
		result1 *op.AccountRecord
		result2 error
	}
	getAccountReturnsOnCall map[int]struct {
		result1 *op.AccountRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAccountStore) AccountName(arg1 context.Context, arg2 string) (string, error) {
	fake.accountNameMutex.Lock()
	ret, specificReturn := fake.accountNameReturnsOnCall[len(fake.accountNameArgsForCall)]
	fake.accountNameArgsForCall = append(fake.accountNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.AccountNameStub
	fakeReturns := fake.accountNameReturns
	fake.recordInvocation("AccountName", []interface{}{arg1, arg2})
	fake.accountNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAccountStore) AccountNameCallCount() int {
	fake.accountNameMutex.RLock()
	defer fake.accountNameMutex.RUnlock()
	return len(fake.accountNameArgsForCall)
}

func (fake *FakeAccountStore) AccountNameCalls(stub func(context.Context, string) (string, error)) {
	fake.accountNameMutex.Lock()
	defer fake.accountNameMutex.Unlock()
	fake.AccountNameStub = stub
}

func (fake *FakeAccountStore) AccountNameArgsForCall(i int) (context.Context, string) {
	fake.accountNameMutex.RLock()
	defer fake.accountNameMutex.RUnlock()
	argsForCall := fake.accountNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAccountStore) AccountNameReturns(result1 string, result2 error) {
	fake.accountNameMutex.Lock()
	defer fake.accountNameMutex.Unlock()
	fake.AccountNameStub = nil
	fake.accountNameReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountStore) AccountNameReturnsOnCall(i int, result1 string, result2 error) {
	fake.accountNameMutex.Lock()
	defer fake.accountNameMutex.Unlock()
	fake.AccountNameStub = nil
	if fake.accountNameReturnsOnCall == nil {
		fake.accountNameReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.accountNameReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountStore) GetAccount(arg1 context.Context, arg2 string) (*op.AccountRecord, error) {
	fake.getAccountMutex.Lock()
	ret, specificReturn := fake.getAccountReturnsOnCall[len(fake.getAccountArgsForCall)]
	fake.getAccountArgsForCall = append(fake.getAccountArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetAccountStub
	fakeReturns := fake.getAccountReturns
	fake.recordInvocation("GetAccount", []interface{}{arg1, arg2})
	fake.getAccountMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAccountStore) GetAccountCallCount() int {
	fake.getAccountMutex.RLock()
	defer fake.getAccountMutex.RUnlock()
	return len(fake.getAccountArgsForCall)
}

func (fake *FakeAccountStore) GetAccountCalls(stub func(context.Context, string) (*op.AccountRecord, error)) {
	fake.getAccountMutex.Lock()
	defer fake.getAccountMutex.Unlock()
	fake.GetAccountStub = stub
}

func (fake *FakeAccountStore) GetAccountArgsForCall(i int) (context.Context, string) {
	fake.getAccountMutex.RLock()
	defer fake.getAccountMutex.RUnlock()
	argsForCall := fake.getAccountArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAccountStore) GetAccountReturns(result1 *op.AccountRecord, result2 error) {
	fake.getAccountMutex.Lock()
	defer fake.getAccountMutex.Unlock()
	fake.GetAccountStub = nil
	fake.getAccountReturns = struct {
		result1 *op.AccountRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountStore) GetAccountReturnsOnCall(i int, result1 *op.AccountRecord, result2 error) {
	fake.getAccountMutex.Lock()
	defer fake.getAccountMutex.Unlock()
	fake.GetAccountStub = nil
	if fake.getAccountReturnsOnCall == nil {
		fake.getAccountReturnsOnCall = make(map[int]struct {
			result1 *op.AccountRecord
			result2 error
		})
	}
	fake.getAccountReturnsOnCall[i] = struct {
		result1 *op.AccountRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAccountStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.AccountStore = new(FakeAccountStore)
