// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeRealmStore struct {
	GetPeriodStub        func(context.Context, string, string, uint32) (meta.Period, error)
	getPeriodMutex       sync.RWMutex
	getPeriodArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 uint32
	}
	getPeriodReturns struct {
		result1 meta.Period
		result2 error
	}
	getPeriodReturnsOnCall map[int]struct {
		result1 meta.Period
		result2 error
	}
	GetPeriodConfigStub        func(context.Context, string) (meta.PeriodConfig, error)
	getPeriodConfigMutex       sync.RWMutex
	getPeriodConfigArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getPeriodConfigReturns struct {
		result1 meta.PeriodConfig
		result2 error
	}
	getPeriodConfigReturnsOnCall map[int]struct {
		result1 meta.PeriodConfig
		result2 error
	}
	GetRealmStub        func(context.Context, string, string) (meta.Realm, error)
	getRealmMutex       sync.RWMutex
	getRealmArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getRealmReturns struct {
		result1 meta.Realm
		result2 error
	}
	getRealmReturnsOnCall map[int]struct {
		result1 meta.Realm
		result2 error
	}
	ListRealmsStub        func(context.Context) (string, []string, error)
	listRealmsMutex       sync.RWMutex
	listRealmsArgsForCall []struct {
		arg1 context.Context
	}
	listRealmsReturns struct {
		result1 string
		result2 []string
		result3 error
	}
	listRealmsReturnsOnCall map[int]struct {
		result1 string
		result2 []string
		result3 error
	}
	PutPeriodConfigStub        func(context.Context, string, meta.PeriodConfig) error
	putPeriodConfigMutex       sync.RWMutex
	putPeriodConfigArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 meta.PeriodConfig
	}
	putPeriodConfigReturns struct {
		result1 error
	}
	putPeriodConfigReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRealmStore) GetPeriod(arg1 context.Context, arg2 string, arg3 string, arg4 uint32) (meta.Period, error) {
	fake.getPeriodMutex.Lock()
	ret, specificReturn := fake.getPeriodReturnsOnCall[len(fake.getPeriodArgsForCall)]
	fake.getPeriodArgsForCall = append(fake.getPeriodArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 uint32
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetPeriodStub
	fakeReturns := fake.getPeriodReturns
	fake.recordInvocation("GetPeriod", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPeriodMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRealmStore) GetPeriodCallCount() int {
	fake.getPeriodMutex.RLock()
	defer fake.getPeriodMutex.RUnlock()
	return len(fake.getPeriodArgsForCall)
}

func (fake *FakeRealmStore) GetPeriodCalls(stub func(context.Context, string, string, uint32) (meta.Period, error)) {
	fake.getPeriodMutex.Lock()
	defer fake.getPeriodMutex.Unlock()
	fake.GetPeriodStub = stub
}

func (fake *FakeRealmStore) GetPeriodArgsForCall(i int) (context.Context, string, string, uint32) {
	fake.getPeriodMutex.RLock()
	defer fake.getPeriodMutex.RUnlock()
	argsForCall := fake.getPeriodArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRealmStore) GetPeriodReturns(result1 meta.Period, result2 error) {
	fake.getPeriodMutex.Lock()
	defer fake.getPeriodMutex.Unlock()
	fake.GetPeriodStub = nil
	fake.getPeriodReturns = struct {
		result1 meta.Period
		result2 error
	}{result1, result2}
}

func (fake *FakeRealmStore) GetPeriodReturnsOnCall(i int, result1 meta.Period, result2 error) {
	fake.getPeriodMutex.Lock()
	defer fake.getPeriodMutex.Unlock()
	fake.GetPeriodStub = nil
	if fake.getPeriodReturnsOnCall == nil {
		fake.getPeriodReturnsOnCall = make(map[int]struct {
			result1 meta.Period
			result2 error
		})
	}
	fake.getPeriodReturnsOnCall[i] = struct {
		result1 meta.Period
		result2 error
	}{result1, result2}
}

func (fake *FakeRealmStore) GetPeriodConfig(arg1 context.Context, arg2 string) (meta.PeriodConfig, error) {
	fake.getPeriodConfigMutex.Lock()
	ret, specificReturn := fake.getPeriodConfigReturnsOnCall[len(fake.getPeriodConfigArgsForCall)]
	fake.getPeriodConfigArgsForCall = append(fake.getPeriodConfigArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetPeriodConfigStub
	fakeReturns := fake.getPeriodConfigReturns
	fake.recordInvocation("GetPeriodConfig", []interface{}{arg1, arg2})
	fake.getPeriodConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRealmStore) GetPeriodConfigCallCount() int {
	fake.getPeriodConfigMutex.RLock()
	defer fake.getPeriodConfigMutex.RUnlock()
	return len(fake.getPeriodConfigArgsForCall)
}

func (fake *FakeRealmStore) GetPeriodConfigCalls(stub func(context.Context, string) (meta.PeriodConfig, error)) {
	fake.getPeriodConfigMutex.Lock()
	defer fake.getPeriodConfigMutex.Unlock()
	fake.GetPeriodConfigStub = stub
}

func (fake *FakeRealmStore) GetPeriodConfigArgsForCall(i int) (context.Context, string) {
	fake.getPeriodConfigMutex.RLock()
	defer fake.getPeriodConfigMutex.RUnlock()
	argsForCall := fake.getPeriodConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRealmStore) GetPeriodConfigReturns(result1 meta.PeriodConfig, result2 error) {
	fake.getPeriodConfigMutex.Lock()
	defer fake.getPeriodConfigMutex.Unlock()
	fake.GetPeriodConfigStub = nil
	fake.getPeriodConfigReturns = struct {
		result1 meta.PeriodConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeRealmStore) GetPeriodConfigReturnsOnCall(i int, result1 meta.PeriodConfig, result2 error) {
	fake.getPeriodConfigMutex.Lock()
	defer fake.getPeriodConfigMutex.Unlock()
	fake.GetPeriodConfigStub = nil
	if fake.getPeriodConfigReturnsOnCall == nil {
		fake.getPeriodConfigReturnsOnCall = make(map[int]struct {
			result1 meta.PeriodConfig
			result2 error
		})
	}
	fake.getPeriodConfigReturnsOnCall[i] = struct {
		result1 meta.PeriodConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeRealmStore) GetRealm(arg1 context.Context, arg2 string, arg3 string) (meta.Realm, error) {
	fake.getRealmMutex.Lock()
	ret, specificReturn := fake.getRealmReturnsOnCall[len(fake.getRealmArgsForCall)]
	fake.getRealmArgsForCall = append(fake.getRealmArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetRealmStub
	fakeReturns := fake.getRealmReturns
	fake.recordInvocation("GetRealm", []interface{}{arg1, arg2, arg3})
	fake.getRealmMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRealmStore) GetRealmCallCount() int {
	fake.getRealmMutex.RLock()
	defer fake.getRealmMutex.RUnlock()
	return len(fake.getRealmArgsForCall)
}

func (fake *FakeRealmStore) GetRealmCalls(stub func(context.Context, string, string) (meta.Realm, error)) {
	fake.getRealmMutex.Lock()
	defer fake.getRealmMutex.Unlock()
	fake.GetRealmStub = stub
}

func (fake *FakeRealmStore) GetRealmArgsForCall(i int) (context.Context, string, string) {
	fake.getRealmMutex.RLock()
	defer fake.getRealmMutex.RUnlock()
	argsForCall := fake.getRealmArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRealmStore) GetRealmReturns(result1 meta.Realm, result2 error) {
	fake.getRealmMutex.Lock()
	defer fake.getRealmMutex.Unlock()
	fake.GetRealmStub = nil
	fake.getRealmReturns = struct {
		result1 meta.Realm
		result2 error
	}{result1, result2}
}

func (fake *FakeRealmStore) GetRealmReturnsOnCall(i int, result1 meta.Realm, result2 error) {
	fake.getRealmMutex.Lock()
	defer fake.getRealmMutex.Unlock()
	fake.GetRealmStub = nil
	if fake.getRealmReturnsOnCall == nil {
		fake.getRealmReturnsOnCall = make(map[int]struct {
			result1 meta.Realm
			result2 error
		})
	}
	fake.getRealmReturnsOnCall[i] = struct {
		result1 meta.Realm
		result2 error
	}{result1, result2}
}

func (fake *FakeRealmStore) ListRealms(arg1 context.Context) (string, []string, error) {
	fake.listRealmsMutex.Lock()
	ret, specificReturn := fake.listRealmsReturnsOnCall[len(fake.listRealmsArgsForCall)]
	fake.listRealmsArgsForCall = append(fake.listRealmsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListRealmsStub
	fakeReturns := fake.listRealmsReturns
	fake.recordInvocation("ListRealms", []interface{}{arg1})
	fake.listRealmsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeRealmStore) ListRealmsCallCount() int {
	fake.listRealmsMutex.RLock()
	defer fake.listRealmsMutex.RUnlock()
	return len(fake.listRealmsArgsForCall)
}

func (fake *FakeRealmStore) ListRealmsCalls(stub func(context.Context) (string, []string, error)) {
	fake.listRealmsMutex.Lock()
	defer fake.listRealmsMutex.Unlock()
	fake.ListRealmsStub = stub
}

func (fake *FakeRealmStore) ListRealmsArgsForCall(i int) context.Context {
	fake.listRealmsMutex.RLock()
	defer fake.listRealmsMutex.RUnlock()
	argsForCall := fake.listRealmsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRealmStore) ListRealmsReturns(result1 string, result2 []string, result3 error) {
	fake.listRealmsMutex.Lock()
	defer fake.listRealmsMutex.Unlock()
	fake.ListRealmsStub = nil
	fake.listRealmsReturns = struct {
		result1 string
		result2 []string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeRealmStore) ListRealmsReturnsOnCall(i int, result1 string, result2 []string, result3 error) {
	fake.listRealmsMutex.Lock()
	defer fake.listRealmsMutex.Unlock()
	fake.ListRealmsStub = nil
	if fake.listRealmsReturnsOnCall == nil {
		fake.listRealmsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 []string
			result3 error
		})
	}
	fake.listRealmsReturnsOnCall[i] = struct {
		result1 string
		result2 []string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeRealmStore) PutPeriodConfig(arg1 context.Context, arg2 string, arg3 meta.PeriodConfig) error {
	fake.putPeriodConfigMutex.Lock()
	ret, specificReturn := fake.putPeriodConfigReturnsOnCall[len(fake.putPeriodConfigArgsForCall)]
	fake.putPeriodConfigArgsForCall = append(fake.putPeriodConfigArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 meta.PeriodConfig
	}{arg1, arg2, arg3})
	stub := fake.PutPeriodConfigStub
	fakeReturns := fake.putPeriodConfigReturns
	fake.recordInvocation("PutPeriodConfig", []interface{}{arg1, arg2, arg3})
	fake.putPeriodConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRealmStore) PutPeriodConfigCallCount() int {
	fake.putPeriodConfigMutex.RLock()
	defer fake.putPeriodConfigMutex.RUnlock()
	return len(fake.putPeriodConfigArgsForCall)
}

func (fake *FakeRealmStore) PutPeriodConfigCalls(stub func(context.Context, string, meta.PeriodConfig) error) {
	fake.putPeriodConfigMutex.Lock()
	defer fake.putPeriodConfigMutex.Unlock()
	fake.PutPeriodConfigStub = stub
}

func (fake *FakeRealmStore) PutPeriodConfigArgsForCall(i int) (context.Context, string, meta.PeriodConfig) {
	fake.putPeriodConfigMutex.RLock()
	defer fake.putPeriodConfigMutex.RUnlock()
	argsForCall := fake.putPeriodConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRealmStore) PutPeriodConfigReturns(result1 error) {
	fake.putPeriodConfigMutex.Lock()
	defer fake.putPeriodConfigMutex.Unlock()
	fake.PutPeriodConfigStub = nil
	fake.putPeriodConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealmStore) PutPeriodConfigReturnsOnCall(i int, result1 error) {
	fake.putPeriodConfigMutex.Lock()
	defer fake.putPeriodConfigMutex.Unlock()
	fake.PutPeriodConfigStub = nil
	if fake.putPeriodConfigReturnsOnCall == nil {
		fake.putPeriodConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putPeriodConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealmStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRealmStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.RealmStore = new(FakeRealmStore)
