// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeStatsStore struct {
	BucketStatsStub        func(context.Context, *op.BucketRecord) (op.Stats, error)
	bucketStatsMutex       sync.RWMutex
	bucketStatsArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}
	bucketStatsReturns struct {
		result1 op.Stats
		result2 error
	}
	bucketStatsReturnsOnCall map[int]struct {
		result1 op.Stats
		result2 error
	}
	CheckQuotaStub        func(context.Context, *op.BucketRecord, meta.Owner, int64, int64) error
	checkQuotaMutex       sync.RWMutex
	checkQuotaArgsForCall []struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
		arg4 int64
		arg5 int64
	}
	checkQuotaReturns struct {
		result1 error
	}
	checkQuotaReturnsOnCall map[int]struct {
		result1 error
	}
	UserStatsStub        func(context.Context, meta.Owner) (op.Stats, error)
	userStatsMutex       sync.RWMutex
	userStatsArgsForCall []struct {
		arg1 context.Context
		arg2 meta.Owner
	}
	userStatsReturns struct {
		result1 op.Stats
		result2 error
	}
	userStatsReturnsOnCall map[int]struct {
		result1 op.Stats
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStatsStore) BucketStats(arg1 context.Context, arg2 *op.BucketRecord) (op.Stats, error) {
	fake.bucketStatsMutex.Lock()
	ret, specificReturn := fake.bucketStatsReturnsOnCall[len(fake.bucketStatsArgsForCall)]
	fake.bucketStatsArgsForCall = append(fake.bucketStatsArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
	}{arg1, arg2})
	stub := fake.BucketStatsStub
	fakeReturns := fake.bucketStatsReturns
	fake.recordInvocation("BucketStats", []interface{}{arg1, arg2})
	fake.bucketStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStatsStore) BucketStatsCallCount() int {
	fake.bucketStatsMutex.RLock()
	defer fake.bucketStatsMutex.RUnlock()
	return len(fake.bucketStatsArgsForCall)
}

func (fake *FakeStatsStore) BucketStatsCalls(stub func(context.Context, *op.BucketRecord) (op.Stats, error)) {
	fake.bucketStatsMutex.Lock()
	defer fake.bucketStatsMutex.Unlock()
	fake.BucketStatsStub = stub
}

func (fake *FakeStatsStore) BucketStatsArgsForCall(i int) (context.Context, *op.BucketRecord) {
	fake.bucketStatsMutex.RLock()
	defer fake.bucketStatsMutex.RUnlock()
	argsForCall := fake.bucketStatsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStatsStore) BucketStatsReturns(result1 op.Stats, result2 error) {
	fake.bucketStatsMutex.Lock()
	defer fake.bucketStatsMutex.Unlock()
	fake.BucketStatsStub = nil
	fake.bucketStatsReturns = struct {
		result1 op.Stats
		result2 error
	}{result1, result2}
}

func (fake *FakeStatsStore) BucketStatsReturnsOnCall(i int, result1 op.Stats, result2 error) {
	fake.bucketStatsMutex.Lock()
	defer fake.bucketStatsMutex.Unlock()
	fake.BucketStatsStub = nil
	if fake.bucketStatsReturnsOnCall == nil {
		fake.bucketStatsReturnsOnCall = make(map[int]struct {
			result1 op.Stats
			result2 error
		})
	}
	fake.bucketStatsReturnsOnCall[i] = struct {
		result1 op.Stats
		result2 error
	}{result1, result2}
}

func (fake *FakeStatsStore) CheckQuota(arg1 context.Context, arg2 *op.BucketRecord, arg3 meta.Owner, arg4 int64, arg5 int64) error {
	fake.checkQuotaMutex.Lock()
	ret, specificReturn := fake.checkQuotaReturnsOnCall[len(fake.checkQuotaArgsForCall)]
	fake.checkQuotaArgsForCall = append(fake.checkQuotaArgsForCall, struct {
		arg1 context.Context
		arg2 *op.BucketRecord
		arg3 meta.Owner
		arg4 int64
		arg5 int64
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.CheckQuotaStub
	fakeReturns := fake.checkQuotaReturns
	fake.recordInvocation("CheckQuota", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.checkQuotaMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStatsStore) CheckQuotaCallCount() int {
	fake.checkQuotaMutex.RLock()
	defer fake.checkQuotaMutex.RUnlock()
	return len(fake.checkQuotaArgsForCall)
}

func (fake *FakeStatsStore) CheckQuotaCalls(stub func(context.Context, *op.BucketRecord, meta.Owner, int64, int64) error) {
	fake.checkQuotaMutex.Lock()
	defer fake.checkQuotaMutex.Unlock()
	fake.CheckQuotaStub = stub
}

func (fake *FakeStatsStore) CheckQuotaArgsForCall(i int) (context.Context, *op.BucketRecord, meta.Owner, int64, int64) {
	fake.checkQuotaMutex.RLock()
	defer fake.checkQuotaMutex.RUnlock()
	argsForCall := fake.checkQuotaArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeStatsStore) CheckQuotaReturns(result1 error) {
	fake.checkQuotaMutex.Lock()
	defer fake.checkQuotaMutex.Unlock()
	fake.CheckQuotaStub = nil
	fake.checkQuotaReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStatsStore) CheckQuotaReturnsOnCall(i int, result1 error) {
	fake.checkQuotaMutex.Lock()
	defer fake.checkQuotaMutex.Unlock()
	fake.CheckQuotaStub = nil
	if fake.checkQuotaReturnsOnCall == nil {
		fake.checkQuotaReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkQuotaReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStatsStore) UserStats(arg1 context.Context, arg2 meta.Owner) (op.Stats, error) {
	fake.userStatsMutex.Lock()
	ret, specificReturn := fake.userStatsReturnsOnCall[len(fake.userStatsArgsForCall)]
	fake.userStatsArgsForCall = append(fake.userStatsArgsForCall, struct {
		arg1 context.Context
		arg2 meta.Owner
	}{arg1, arg2})
	stub := fake.UserStatsStub
	fakeReturns := fake.userStatsReturns
	fake.recordInvocation("UserStats", []interface{}{arg1, arg2})
	fake.userStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStatsStore) UserStatsCallCount() int {
	fake.userStatsMutex.RLock()
	defer fake.userStatsMutex.RUnlock()
	return len(fake.userStatsArgsForCall)
}

func (fake *FakeStatsStore) UserStatsCalls(stub func(context.Context, meta.Owner) (op.Stats, error)) {
	fake.userStatsMutex.Lock()
	defer fake.userStatsMutex.Unlock()
	fake.UserStatsStub = stub
}

func (fake *FakeStatsStore) UserStatsArgsForCall(i int) (context.Context, meta.Owner) {
	fake.userStatsMutex.RLock()
	defer fake.userStatsMutex.RUnlock()
	argsForCall := fake.userStatsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStatsStore) UserStatsReturns(result1 op.Stats, result2 error) {
	fake.userStatsMutex.Lock()
	defer fake.userStatsMutex.Unlock()
	fake.UserStatsStub = nil
	fake.userStatsReturns = struct {
		result1 op.Stats
		result2 error
	}{result1, result2}
}

func (fake *FakeStatsStore) UserStatsReturnsOnCall(i int, result1 op.Stats, result2 error) {
	fake.userStatsMutex.Lock()
	defer fake.userStatsMutex.Unlock()
	fake.UserStatsStub = nil
	if fake.userStatsReturnsOnCall == nil {
		fake.userStatsReturnsOnCall = make(map[int]struct {
			result1 op.Stats
			result2 error
		})
	}
	fake.userStatsReturnsOnCall[i] = struct {
		result1 op.Stats
		result2 error
	}{result1, result2}
}

func (fake *FakeStatsStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStatsStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.StatsStore = new(FakeStatsStore)
