// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/rgw-go/internal/meta"
	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeUserStore struct {
	FindKeyHolderStub        func(context.Context, string) (meta.UserID, error)
	findKeyHolderMutex       sync.RWMutex
	findKeyHolderArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findKeyHolderReturns struct {
		result1 meta.UserID
		result2 error
	}
	findKeyHolderReturnsOnCall map[int]struct {
		result1 meta.UserID
		result2 error
	}
	GetUserStub        func(context.Context, meta.UserID) (*op.UserRecord, error)
	getUserMutex       sync.RWMutex
	getUserArgsForCall []struct {
		arg1 context.Context
		arg2 meta.UserID
	}
	getUserReturns struct {
		result1 *op.UserRecord
		result2 error
	}
	getUserReturnsOnCall map[int]struct {
		result1 *op.UserRecord
		result2 error
	}
	GetUserByAccessKeyStub        func(context.Context, string) (*op.UserRecord, error)
	getUserByAccessKeyMutex       sync.RWMutex
	getUserByAccessKeyArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getUserByAccessKeyReturns struct {
		result1 *op.UserRecord
		result2 error
	}
	getUserByAccessKeyReturnsOnCall map[int]struct {
		result1 *op.UserRecord
		result2 error
	}
	GetUserByEmailStub        func(context.Context, string) (*op.UserRecord, error)
	getUserByEmailMutex       sync.RWMutex
	getUserByEmailArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getUserByEmailReturns struct {
		result1 *op.UserRecord
		result2 error
	}
	getUserByEmailReturnsOnCall map[int]struct {
		result1 *op.UserRecord
		result2 error
	}
	ListUserBucketsStub        func(context.Context, meta.Owner, string, int) ([]meta.BucketEnt, string, bool, error)
	listUserBucketsMutex       sync.RWMutex
	listUserBucketsArgsForCall []struct {
		arg1 context.Context
		arg2 meta.Owner
		arg3 string
		arg4 int
	}
	listUserBucketsReturns struct {
		result1 []meta.BucketEnt
		result2 string
		result3 bool
		result4 error
	}
	listUserBucketsReturnsOnCall map[int]struct {
		result1 []meta.BucketEnt
		result2 string
		result3 bool
		result4 error
	}
	PutUserStub        func(context.Context, *op.UserRecord, op.PutUserOptions) error
	putUserMutex       sync.RWMutex
	putUserArgsForCall []struct {
		arg1 context.Context
		arg2 *op.UserRecord
		arg3 op.PutUserOptions
	}
	putUserReturns struct {
		result1 error
	}
	putUserReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveUserStub        func(context.Context, *op.UserRecord) error
	removeUserMutex       sync.RWMutex
	removeUserArgsForCall []struct {
		arg1 context.Context
		arg2 *op.UserRecord
	}
	removeUserReturns struct {
		result1 error
	}
	removeUserReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUserStore) FindKeyHolder(arg1 context.Context, arg2 string) (meta.UserID, error) {
	fake.findKeyHolderMutex.Lock()
	ret, specificReturn := fake.findKeyHolderReturnsOnCall[len(fake.findKeyHolderArgsForCall)]
	fake.findKeyHolderArgsForCall = append(fake.findKeyHolderArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindKeyHolderStub
	fakeReturns := fake.findKeyHolderReturns
	fake.recordInvocation("FindKeyHolder", []interface{}{arg1, arg2})
	fake.findKeyHolderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserStore) FindKeyHolderCallCount() int {
	fake.findKeyHolderMutex.RLock()
	defer fake.findKeyHolderMutex.RUnlock()
	return len(fake.findKeyHolderArgsForCall)
}

func (fake *FakeUserStore) FindKeyHolderCalls(stub func(context.Context, string) (meta.UserID, error)) {
	fake.findKeyHolderMutex.Lock()
	defer fake.findKeyHolderMutex.Unlock()
	fake.FindKeyHolderStub = stub
}

func (fake *FakeUserStore) FindKeyHolderArgsForCall(i int) (context.Context, string) {
	fake.findKeyHolderMutex.RLock()
	defer fake.findKeyHolderMutex.RUnlock()
	argsForCall := fake.findKeyHolderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserStore) FindKeyHolderReturns(result1 meta.UserID, result2 error) {
	fake.findKeyHolderMutex.Lock()
	defer fake.findKeyHolderMutex.Unlock()
	fake.FindKeyHolderStub = nil
	fake.findKeyHolderReturns = struct {
		result1 meta.UserID
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) FindKeyHolderReturnsOnCall(i int, result1 meta.UserID, result2 error) {
	fake.findKeyHolderMutex.Lock()
	defer fake.findKeyHolderMutex.Unlock()
	fake.FindKeyHolderStub = nil
	if fake.findKeyHolderReturnsOnCall == nil {
		fake.findKeyHolderReturnsOnCall = make(map[int]struct {
			result1 meta.UserID
			result2 error
		})
	}
	fake.findKeyHolderReturnsOnCall[i] = struct {
		result1 meta.UserID
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) GetUser(arg1 context.Context, arg2 meta.UserID) (*op.UserRecord, error) {
	fake.getUserMutex.Lock()
	ret, specificReturn := fake.getUserReturnsOnCall[len(fake.getUserArgsForCall)]
	fake.getUserArgsForCall = append(fake.getUserArgsForCall, struct {
		arg1 context.Context
		arg2 meta.UserID
	}{arg1, arg2})
	stub := fake.GetUserStub
	fakeReturns := fake.getUserReturns
	fake.recordInvocation("GetUser", []interface{}{arg1, arg2})
	fake.getUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserStore) GetUserCallCount() int {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	return len(fake.getUserArgsForCall)
}

func (fake *FakeUserStore) GetUserCalls(stub func(context.Context, meta.UserID) (*op.UserRecord, error)) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = stub
}

func (fake *FakeUserStore) GetUserArgsForCall(i int) (context.Context, meta.UserID) {
	fake.getUserMutex.RLock()
	defer fake.getUserMutex.RUnlock()
	argsForCall := fake.getUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserStore) GetUserReturns(result1 *op.UserRecord, result2 error) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = nil
	fake.getUserReturns = struct {
		result1 *op.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) GetUserReturnsOnCall(i int, result1 *op.UserRecord, result2 error) {
	fake.getUserMutex.Lock()
	defer fake.getUserMutex.Unlock()
	fake.GetUserStub = nil
	if fake.getUserReturnsOnCall == nil {
		fake.getUserReturnsOnCall = make(map[int]struct {
			result1 *op.UserRecord
			result2 error
		})
	}
	fake.getUserReturnsOnCall[i] = struct {
		result1 *op.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) GetUserByAccessKey(arg1 context.Context, arg2 string) (*op.UserRecord, error) {
	fake.getUserByAccessKeyMutex.Lock()
	ret, specificReturn := fake.getUserByAccessKeyReturnsOnCall[len(fake.getUserByAccessKeyArgsForCall)]
	fake.getUserByAccessKeyArgsForCall = append(fake.getUserByAccessKeyArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetUserByAccessKeyStub
	fakeReturns := fake.getUserByAccessKeyReturns
	fake.recordInvocation("GetUserByAccessKey", []interface{}{arg1, arg2})
	fake.getUserByAccessKeyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserStore) GetUserByAccessKeyCallCount() int {
	fake.getUserByAccessKeyMutex.RLock()
	defer fake.getUserByAccessKeyMutex.RUnlock()
	return len(fake.getUserByAccessKeyArgsForCall)
}

func (fake *FakeUserStore) GetUserByAccessKeyCalls(stub func(context.Context, string) (*op.UserRecord, error)) {
	fake.getUserByAccessKeyMutex.Lock()
	defer fake.getUserByAccessKeyMutex.Unlock()
	fake.GetUserByAccessKeyStub = stub
}

func (fake *FakeUserStore) GetUserByAccessKeyArgsForCall(i int) (context.Context, string) {
	fake.getUserByAccessKeyMutex.RLock()
	defer fake.getUserByAccessKeyMutex.RUnlock()
	argsForCall := fake.getUserByAccessKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserStore) GetUserByAccessKeyReturns(result1 *op.UserRecord, result2 error) {
	fake.getUserByAccessKeyMutex.Lock()
	defer fake.getUserByAccessKeyMutex.Unlock()
	fake.GetUserByAccessKeyStub = nil
	fake.getUserByAccessKeyReturns = struct {
		result1 *op.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) GetUserByAccessKeyReturnsOnCall(i int, result1 *op.UserRecord, result2 error) {
	fake.getUserByAccessKeyMutex.Lock()
	defer fake.getUserByAccessKeyMutex.Unlock()
	fake.GetUserByAccessKeyStub = nil
	if fake.getUserByAccessKeyReturnsOnCall == nil {
		fake.getUserByAccessKeyReturnsOnCall = make(map[int]struct {
			result1 *op.UserRecord
			result2 error
		})
	}
	fake.getUserByAccessKeyReturnsOnCall[i] = struct {
		result1 *op.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) GetUserByEmail(arg1 context.Context, arg2 string) (*op.UserRecord, error) {
	fake.getUserByEmailMutex.Lock()
	ret, specificReturn := fake.getUserByEmailReturnsOnCall[len(fake.getUserByEmailArgsForCall)]
	fake.getUserByEmailArgsForCall = append(fake.getUserByEmailArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetUserByEmailStub
	fakeReturns := fake.getUserByEmailReturns
	fake.recordInvocation("GetUserByEmail", []interface{}{arg1, arg2})
	fake.getUserByEmailMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeUserStore) GetUserByEmailCallCount() int {
	fake.getUserByEmailMutex.RLock()
	defer fake.getUserByEmailMutex.RUnlock()
	return len(fake.getUserByEmailArgsForCall)
}

func (fake *FakeUserStore) GetUserByEmailCalls(stub func(context.Context, string) (*op.UserRecord, error)) {
	fake.getUserByEmailMutex.Lock()
	defer fake.getUserByEmailMutex.Unlock()
	fake.GetUserByEmailStub = stub
}

func (fake *FakeUserStore) GetUserByEmailArgsForCall(i int) (context.Context, string) {
	fake.getUserByEmailMutex.RLock()
	defer fake.getUserByEmailMutex.RUnlock()
	argsForCall := fake.getUserByEmailArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserStore) GetUserByEmailReturns(result1 *op.UserRecord, result2 error) {
	fake.getUserByEmailMutex.Lock()
	defer fake.getUserByEmailMutex.Unlock()
	fake.GetUserByEmailStub = nil
	fake.getUserByEmailReturns = struct {
		result1 *op.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) GetUserByEmailReturnsOnCall(i int, result1 *op.UserRecord, result2 error) {
	fake.getUserByEmailMutex.Lock()
	defer fake.getUserByEmailMutex.Unlock()
	fake.GetUserByEmailStub = nil
	if fake.getUserByEmailReturnsOnCall == nil {
		fake.getUserByEmailReturnsOnCall = make(map[int]struct {
			result1 *op.UserRecord
			result2 error
		})
	}
	fake.getUserByEmailReturnsOnCall[i] = struct {
		result1 *op.UserRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeUserStore) ListUserBuckets(arg1 context.Context, arg2 meta.Owner, arg3 string, arg4 int) ([]meta.BucketEnt, string, bool, error) {
	fake.listUserBucketsMutex.Lock()
	ret, specificReturn := fake.listUserBucketsReturnsOnCall[len(fake.listUserBucketsArgsForCall)]
	fake.listUserBucketsArgsForCall = append(fake.listUserBucketsArgsForCall, struct {
		arg1 context.Context
		arg2 meta.Owner
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListUserBucketsStub
	fakeReturns := fake.listUserBucketsReturns
	fake.recordInvocation("ListUserBuckets", []interface{}{arg1, arg2, arg3, arg4})
	fake.listUserBucketsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3, ret.result4
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3, fakeReturns.result4
}

func (fake *FakeUserStore) ListUserBucketsCallCount() int {
	fake.listUserBucketsMutex.RLock()
	defer fake.listUserBucketsMutex.RUnlock()
	return len(fake.listUserBucketsArgsForCall)
}

func (fake *FakeUserStore) ListUserBucketsCalls(stub func(context.Context, meta.Owner, string, int) ([]meta.BucketEnt, string, bool, error)) {
	fake.listUserBucketsMutex.Lock()
	defer fake.listUserBucketsMutex.Unlock()
	fake.ListUserBucketsStub = stub
}

func (fake *FakeUserStore) ListUserBucketsArgsForCall(i int) (context.Context, meta.Owner, string, int) {
	fake.listUserBucketsMutex.RLock()
	defer fake.listUserBucketsMutex.RUnlock()
	argsForCall := fake.listUserBucketsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeUserStore) ListUserBucketsReturns(result1 []meta.BucketEnt, result2 string, result3 bool, result4 error) {
	fake.listUserBucketsMutex.Lock()
	defer fake.listUserBucketsMutex.Unlock()
	fake.ListUserBucketsStub = nil
	fake.listUserBucketsReturns = struct {
		result1 []meta.BucketEnt
		result2 string
		result3 bool
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *FakeUserStore) ListUserBucketsReturnsOnCall(i int, result1 []meta.BucketEnt, result2 string, result3 bool, result4 error) {
	fake.listUserBucketsMutex.Lock()
	defer fake.listUserBucketsMutex.Unlock()
	fake.ListUserBucketsStub = nil
	if fake.listUserBucketsReturnsOnCall == nil {
		fake.listUserBucketsReturnsOnCall = make(map[int]struct {
			result1 []meta.BucketEnt
			result2 string
			result3 bool
			result4 error
		})
	}
	fake.listUserBucketsReturnsOnCall[i] = struct {
		result1 []meta.BucketEnt
		result2 string
		result3 bool
		result4 error
	}{result1, result2, result3, result4}
}

func (fake *FakeUserStore) PutUser(arg1 context.Context, arg2 *op.UserRecord, arg3 op.PutUserOptions) error {
	fake.putUserMutex.Lock()
	ret, specificReturn := fake.putUserReturnsOnCall[len(fake.putUserArgsForCall)]
	fake.putUserArgsForCall = append(fake.putUserArgsForCall, struct {
		arg1 context.Context
		arg2 *op.UserRecord
		arg3 op.PutUserOptions
	}{arg1, arg2, arg3})
	stub := fake.PutUserStub
	fakeReturns := fake.putUserReturns
	fake.recordInvocation("PutUser", []interface{}{arg1, arg2, arg3})
	fake.putUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeUserStore) PutUserCallCount() int {
	fake.putUserMutex.RLock()
	defer fake.putUserMutex.RUnlock()
	return len(fake.putUserArgsForCall)
}

func (fake *FakeUserStore) PutUserCalls(stub func(context.Context, *op.UserRecord, op.PutUserOptions) error) {
	fake.putUserMutex.Lock()
	defer fake.putUserMutex.Unlock()
	fake.PutUserStub = stub
}

func (fake *FakeUserStore) PutUserArgsForCall(i int) (context.Context, *op.UserRecord, op.PutUserOptions) {
	fake.putUserMutex.RLock()
	defer fake.putUserMutex.RUnlock()
	argsForCall := fake.putUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeUserStore) PutUserReturns(result1 error) {
	fake.putUserMutex.Lock()
	defer fake.putUserMutex.Unlock()
	fake.PutUserStub = nil
	fake.putUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserStore) PutUserReturnsOnCall(i int, result1 error) {
	fake.putUserMutex.Lock()
	defer fake.putUserMutex.Unlock()
	fake.PutUserStub = nil
	if fake.putUserReturnsOnCall == nil {
		fake.putUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserStore) RemoveUser(arg1 context.Context, arg2 *op.UserRecord) error {
	fake.removeUserMutex.Lock()
	ret, specificReturn := fake.removeUserReturnsOnCall[len(fake.removeUserArgsForCall)]
	fake.removeUserArgsForCall = append(fake.removeUserArgsForCall, struct {
		arg1 context.Context
		arg2 *op.UserRecord
	}{arg1, arg2})
	stub := fake.RemoveUserStub
	fakeReturns := fake.removeUserReturns
	fake.recordInvocation("RemoveUser", []interface{}{arg1, arg2})
	fake.removeUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeUserStore) RemoveUserCallCount() int {
	fake.removeUserMutex.RLock()
	defer fake.removeUserMutex.RUnlock()
	return len(fake.removeUserArgsForCall)
}

func (fake *FakeUserStore) RemoveUserCalls(stub func(context.Context, *op.UserRecord) error) {
	fake.removeUserMutex.Lock()
	defer fake.removeUserMutex.Unlock()
	fake.RemoveUserStub = stub
}

func (fake *FakeUserStore) RemoveUserArgsForCall(i int) (context.Context, *op.UserRecord) {
	fake.removeUserMutex.RLock()
	defer fake.removeUserMutex.RUnlock()
	argsForCall := fake.removeUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeUserStore) RemoveUserReturns(result1 error) {
	fake.removeUserMutex.Lock()
	defer fake.removeUserMutex.Unlock()
	fake.RemoveUserStub = nil
	fake.removeUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserStore) RemoveUserReturnsOnCall(i int, result1 error) {
	fake.removeUserMutex.Lock()
	defer fake.removeUserMutex.Unlock()
	fake.RemoveUserStub = nil
	if fake.removeUserReturnsOnCall == nil {
		fake.removeUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUserStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUserStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.UserStore = new(FakeUserStore)
