// Code generated by counterfeiter. DO NOT EDIT.
package opfakes

import (
	"sync"
	"time"

	"github.com/jhoblitt/rgw-go/internal/op"
)

type FakeMetrics struct {
	InFlightStub        func(int)
	inFlightMutex       sync.RWMutex
	inFlightArgsForCall []struct {
		arg1 int
	}
	ObserveStub        func(string, int, time.Duration, int64, int64)
	observeMutex       sync.RWMutex
	observeArgsForCall []struct {
		arg1 string
		arg2 int
		arg3 time.Duration
		arg4 int64
		arg5 int64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMetrics) InFlight(arg1 int) {
	fake.inFlightMutex.Lock()
	fake.inFlightArgsForCall = append(fake.inFlightArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.InFlightStub
	fake.recordInvocation("InFlight", []interface{}{arg1})
	fake.inFlightMutex.Unlock()
	if stub != nil {
		fake.InFlightStub(arg1)
	}
}

func (fake *FakeMetrics) InFlightCallCount() int {
	fake.inFlightMutex.RLock()
	defer fake.inFlightMutex.RUnlock()
	return len(fake.inFlightArgsForCall)
}

func (fake *FakeMetrics) InFlightCalls(stub func(int)) {
	fake.inFlightMutex.Lock()
	defer fake.inFlightMutex.Unlock()
	fake.InFlightStub = stub
}

func (fake *FakeMetrics) InFlightArgsForCall(i int) int {
	fake.inFlightMutex.RLock()
	defer fake.inFlightMutex.RUnlock()
	argsForCall := fake.inFlightArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMetrics) Observe(arg1 string, arg2 int, arg3 time.Duration, arg4 int64, arg5 int64) {
	fake.observeMutex.Lock()
	fake.observeArgsForCall = append(fake.observeArgsForCall, struct {
		arg1 string
		arg2 int
		arg3 time.Duration
		arg4 int64
		arg5 int64
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ObserveStub
	fake.recordInvocation("Observe", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.observeMutex.Unlock()
	if stub != nil {
		fake.ObserveStub(arg1, arg2, arg3, arg4, arg5)
	}
}

func (fake *FakeMetrics) ObserveCallCount() int {
	fake.observeMutex.RLock()
	defer fake.observeMutex.RUnlock()
	return len(fake.observeArgsForCall)
}

func (fake *FakeMetrics) ObserveCalls(stub func(string, int, time.Duration, int64, int64)) {
	fake.observeMutex.Lock()
	defer fake.observeMutex.Unlock()
	fake.ObserveStub = stub
}

func (fake *FakeMetrics) ObserveArgsForCall(i int) (string, int, time.Duration, int64, int64) {
	fake.observeMutex.RLock()
	defer fake.observeMutex.RUnlock()
	argsForCall := fake.observeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ op.Metrics = new(FakeMetrics)
